// src/config/icons.js
// Hub centralisé des exports Lucide React.
// Les nouveaux composants importent d'ici plutôt que directement de 'lucide-react'.

import {
    // Navigation & actions
    ArrowLeft,
    ChevronDown,
    ChevronUp,
    X,
    XCircle,
    Plus,
    PlusCircle,
    Minus,
    Save,
    Download,
    Upload,
    Share,
    Share2,
    Copy,
    ExternalLink,
    Edit,
    Trash2,
    Send,
    Printer,
    RotateCcw,
    RefreshCcw,
    LogOut,

    // État & feedback
    Check,
    CheckCheck,
    CheckCircle,
    CheckCircle2,
    AlertCircle,
    AlertTriangle,
    Info,
    HelpCircle,
    ShieldAlert,
    Clock,
    Loader,
    Moon,
    Sun,

    // Utilisateurs & social
    User,
    Users,
    Mail,
    MessageCircle,
    Inbox,
    Globe,

    // Sécurité & rôles
    Lock,
    Unlock,
    Key,
    Shield,
    ShieldCheck,
    Crown,

    // Contenus & données
    BookOpen,
    Book,
    BookMarked,
    FileText,
    Archive,
    Tag,
    Filter,
    ListFilter,
    LayoutList,
    Search,
    List,
    ZoomIn,
    ZoomOut,

    // Jeu & féérique
    Sparkles,
    Star,
    Feather,
    Zap,
    Wand2,
    VenetianMask,
    Dices,
    Brain,

    // Statistiques & business
    Activity,
    BarChart2,
    TrendingUp,
    TrendingDown,
    GitMerge,
    Settings,
    TestTubeDiagonal,

    // UI spécifique
    Award,
    Gem,
    Gift,
    Heart,
    Briefcase,
    Coins,
    ShoppingBag,
    Package,
    MapPin,
    Scaling,
    Calendar,
    Camera,

    // Médias
    Eye,
    EyeOff,
    Image,

    // Actions contextuelles
    ThumbsUp,
    ThumbsDown,
    Bug,
    Bell,
    BellOff,
    Smartphone,
    Palette,
    Wrench,
    FolderOpen,
    Hammer,
    Map,
    Navigation,
    Route,
    Menu,
    UtensilsCrossed,
    Wine,
} from 'lucide-react';

export {
    ArrowLeft, ChevronDown, ChevronUp, X, XCircle, Plus, PlusCircle, Minus,
    Save, Download, Upload, Share, Share2, Copy, ExternalLink, Edit, Trash2,
    Send, Printer, RotateCcw, RefreshCcw, LogOut,
    Check, CheckCheck, CheckCircle, CheckCircle2, AlertCircle, AlertTriangle,
    Info, HelpCircle, ShieldAlert, Clock, Loader, Moon, Sun,
    User, Users, Mail, MessageCircle, Inbox, Globe,
    Lock, Unlock, Key, Shield, ShieldCheck, Crown,
    BookOpen, Book, BookMarked, FileText, Archive, Tag, Filter, ListFilter, LayoutList,
    Search, List, ZoomIn, ZoomOut,
    Sparkles, Star, Feather, Zap, Wand2, VenetianMask, Dices, Brain,
    Activity, BarChart2, TrendingUp, TrendingDown, GitMerge, Settings, TestTubeDiagonal,
    Award, Gem, Gift, Heart, Briefcase, Coins, ShoppingBag, Package, MapPin,
    Scaling, Calendar, Camera,
    Eye, EyeOff, Image,
    ThumbsUp, ThumbsDown, Bug, Bell, BellOff, Smartphone, Palette, Wrench, FolderOpen,
    Hammer, Map, Navigation, Route, Menu, UtensilsCrossed, Wine,
};

export const iconMap = {
    ArrowLeft, ChevronDown, ChevronUp, X, XCircle, Plus, PlusCircle, Minus,
    Save, Download, Upload, Share, Share2, Copy, ExternalLink, Edit, Trash2,
    Send, Printer, RotateCcw, RefreshCcw, LogOut,
    Check, CheckCheck, CheckCircle, CheckCircle2, AlertCircle, AlertTriangle,
    Info, HelpCircle, ShieldAlert, Clock, Loader, Moon, Sun,
    User, Users, Mail, MessageCircle, Inbox, Globe,
    Lock, Unlock, Key, Shield, ShieldCheck, Crown,
    BookOpen, Book, BookMarked, FileText, Archive, Tag, Filter, ListFilter, LayoutList,
    Search, List, ZoomIn, ZoomOut,
    Sparkles, Star, Feather, Zap, Wand2, VenetianMask, Dices, Brain,
    Activity, BarChart2, TrendingUp, TrendingDown, GitMerge, Settings, TestTubeDiagonal,
    Award, Gem, Gift, Heart, Briefcase, Coins, ShoppingBag, Package, MapPin,
    Scaling, Calendar, Camera,
    Eye, EyeOff, Image,
    ThumbsUp, ThumbsDown, Bug, Bell, BellOff, Smartphone, Palette, Wrench, FolderOpen,
    Hammer, Map, Navigation, Route, Menu, UtensilsCrossed, Wine,
};
