// scripts/menu_seed_data.js
// Corpus de bootstrap du Générateur de Menu — plats et structures de repas, Belle Époque (1899-1900).

const TOUTES_SAISONS = ['printemps', 'ete', 'automne', 'hiver'];
const FROID = ['automne', 'hiver'];
const CHAUD = ['printemps', 'ete'];

const N_TOUS = ['populaire', 'bourgeois', 'grande_bourgeoisie', 'aristocratie'];
const N_POP = ['populaire', 'bourgeois'];
const N_MOYEN = ['bourgeois', 'grande_bourgeoisie'];
const N_HAUT = ['grande_bourgeoisie', 'aristocratie'];
const N_ARISTO = ['aristocratie'];
const N_BOURG_HAUT = ['bourgeois', 'grande_bourgeoisie', 'aristocratie'];

function plat(nom, categorie, niveaux, saisons, difficulte, accord_vin, narrative, rc, ep, ec) {
  return {
    nom, categorie, niveaux, saisons,
    nb_convives_min: null, nb_convives_max: null,
    difficulte, accord_vin: accord_vin || null,
    description_narrative: narrative || null,
    description_reussite_critique: rc || null,
    description_echec_partiel: ep || null,
    description_echec_critique: ec || null,
  };
}

const plats = [
  // ── BOISSON_CHAUDE (6) ──────────────────────────────────────────────
  plat('Café noir des Colonies', 'boisson_chaude', N_TOUS, TOUTES_SAISONS, 1, null,
    "Une vapeur âcre et chaude s'élève de la cafetière en cuivre.",
    'Le café coule, corsé et parfumé à souhait, un vrai régal pour les narines.',
    "Le café est un peu fade, mais réchauffe tout de même.",
    "Le café a brûlé au fond de la cafetière et tourne à l'amer."),
  plat('Chocolat chaud à la cannelle', 'boisson_chaude', N_MOYEN, FROID, 1, null,
    'Le chocolat fume doucement, épaissi de crème et parfumé de cannelle.',
    'Onctueux à souhait, ce chocolat ferait fondre le cœur le plus endurci.',
    'Le chocolat est un peu grumeleux mais reste buvable.',
    'Le chocolat a tourné et forme une peau désagréable à la surface.'),
  plat('Thé de Chine au jasmin', 'boisson_chaude', N_HAUT, TOUTES_SAISONS, 2, null,
    'Une délicate fragrance de fleurs blanches embaume le salon.',
    "L'infusion est d'une clarté et d'un parfum dignes d'un mandarin.",
    'Le thé a infusé un peu trop longtemps et devient astringent.',
    "Le thé est infusé dans une eau bouillante qui en gâte tout le bouquet."),
  plat('Tisane de tilleul et miel', 'boisson_chaude', N_TOUS, FROID, 1, null,
    "Une infusion dorée et apaisante, parfumée d'un soupçon de miel.",
    'La tisane apaise instantanément et embaume toute la pièce.',
    "Le miel ne s'est pas bien dissous et reste au fond de la tasse.",
    "La tisane est infusée avec des feuilles trop vieilles, amère et terne."),
  plat('Café au lait du matin', 'boisson_chaude', N_TOUS, TOUTES_SAISONS, 1, null,
    'Le bol fume, moitié café moitié lait, prêt pour être trempé de pain.',
    "Un équilibre parfait entre la force du café et la douceur du lait.",
    "Le lait a un peu tranché en surface mais le goût reste correct.",
    'Le lait a tourné en versant le café brûlant, formant des grumeaux.'),
  plat('Infusion de verveine citronnée', 'boisson_chaude', N_MOYEN, CHAUD, 1, null,
    "Un parfum citronné s'échappe de la théière en porcelaine.",
    "L'infusion est limpide, vivifiante, un vrai rayon de soleil en tasse.",
    "L'infusion est un peu fade, les feuilles n'étaient pas assez fraîches.",
    "L'eau était encore bouillante et a brûlé tout l'arôme des feuilles."),

  // ── VIENNOISERIE (10) ───────────────────────────────────────────────
  plat('Croissant au beurre', 'viennoiserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Le croissant doré craque sous la dent, feuilleté à souhait.',
    'Un feuilletage parfait, croustillant dehors, fondant dedans.',
    'Le croissant manque un peu de feuilletage mais reste savoureux.',
    "Le beurre n'a pas bien fondu dans la pâte : le croissant est lourd et compact."),
  plat('Brioche de Nanterre', 'viennoiserie', N_POP, TOUTES_SAISONS, 1, null,
    'Une brioche dorée, moelleuse, tranchée en belles parts.',
    'La mie est filante et le goût de beurre se devine à chaque bouchée.',
    'La brioche est un peu sèche mais agréable trempée dans le café.',
    "La pâte n'a pas assez levé : la brioche est dense comme du pain perdu raté."),
  plat('Pain au chocolat', 'viennoiserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Deux barres de chocolat noir nichées dans une pâte feuilletée.',
    'Le chocolat a fondu juste comme il faut, coulant légèrement à la coupe.',
    'Le feuilletage est un peu mou, mais le chocolat sauve le tout.',
    'Le chocolat a brûlé pendant la cuisson et donne un goût amer.'),
  plat('Chausson aux pommes', 'viennoiserie', N_POP, FROID, 1, null,
    'Une demi-lune dorée, gonflée de compote de pommes parfumée.',
    'La compote, parfumée à la cannelle, embaume sous une pâte dorée à point.',
    'La pâte est un peu pâle, pas assez dorée au four.',
    'La compote a débordé et brûlé, collant le chausson à la plaque.'),
  plat('Madeleine de Commercy', 'viennoiserie', N_HAUT, TOUTES_SAISONS, 2, null,
    "De petites coquilles dorées, à la bosse bien formée.",
    "La bosse caractéristique est parfaite, signe d'une cuisson maîtrisée.",
    "Les madeleines sont un peu plates, la bosse n'a pas pris.",
    "Les madeleines sont restées collées au moule et se brisent en morceaux."),
  plat('Pain perdu doré', 'viennoiserie', N_POP, TOUTES_SAISONS, 1, null,
    'Des tranches de pain rassis, trempées et dorées à la poêle.',
    'Le pain perdu est moelleux à cœur, doré et sucré juste ce qu\'il faut.',
    'Le pain est un peu détrempé, mais le goût reste plaisant.',
    'Le pain est resté trop longtemps dans le lait et se défait à la cuisson.'),
  plat('Galette bretonne', 'viennoiserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Un sablé épais, parfumé au beurre salé, craquant sous la dent.',
    "Le beurre salé ressort à merveille, un sablé d'une finesse rare.",
    'La galette est un peu trop cuite sur les bords.',
    'La pâte trop travaillée donne une galette dure comme de la pierre.'),
  plat('Couque aux raisins', 'viennoiserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Une spirale feuilletée, piquetée de raisins gonflés au rhum.',
    'Les raisins, bien gonflés, fondent dans une pâte parfaitement feuilletée.',
    'Les raisins sont un peu secs, mais la pâte reste bonne.',
    "La crème pâtissière n'a pas pris et coule hors de la pâte."),
  plat('Kouglof alsacien', 'viennoiserie', N_HAUT, FROID, 3, null,
    'Un haut gâteau moulé en couronne, saupoudré de sucre glace.',
    'La mie, légère et parfumée au kirsch, ravit toute la tablée.',
    'Le kouglof est un peu sec, mais le parfum reste au rendez-vous.',
    "La pâte n'a pas levé dans le moule : le kouglof reste plat et lourd."),
  plat("Pain d'épice maison", 'viennoiserie', N_POP, FROID, 1, null,
    "Une tranche dorée et parfumée de miel et d'épices d'Orient.",
    "Le miel et les épices se marient à la perfection dans une mie moelleuse.",
    "Le pain d'épice est un peu sec sur les bords.",
    "Trop d'épices ont été versées : le pain d'épice pique la gorge."),

  // ── POTAGE (20) ─────────────────────────────────────────────────────
  plat('Potage Crécy', 'potage', N_TOUS, TOUTES_SAISONS, 1, "Un petit vin blanc sec",
    "Une crème orangée, douce et veloutée, monte en fumée du potage.",
    "Le velouté de carottes est d'une douceur et d'une couleur parfaites.",
    "Le potage est un peu trop liquide mais le goût reste agréable.",
    "Les carottes ont attaché au fond de la marmite, donnant un goût de brûlé."),
  plat('Potage Parmentier', 'potage', N_POP, TOUTES_SAISONS, 1, null,
    'Un velouté blanc de pommes de terre et de poireaux.',
    "Le potage est crémeux à souhait, réconfortant comme nul autre.",
    'Le potage manque un peu de sel mais reste honnête.',
    "Les poireaux n'ont pas été bien lavés : le potage grince sous la dent."),
  plat('Potage Saint-Germain', 'potage', N_MOYEN, CHAUD, 2, "Un sauvignon vif",
    'Un velouté vert tendre de petits pois frais.',
    "La couleur et la fraîcheur des petits pois subliment ce potage printanier.",
    "Le potage a perdu un peu de sa couleur en cuisant trop longtemps.",
    "Les pois étaient trop vieux : le potage est terne et fade."),
  plat('Soupe à l\'oignon gratinée', 'potage', N_POP, FROID, 2, "Un vin rouge léger",
    'Une croûte de fromage doré recouvre un bouillon brun et parfumé.',
    'Le fromage gratiné forme une croûte filante absolument irrésistible.',
    "Le fromage n'a pas bien gratiné, restant pâle et mou.",
    "Les oignons ont brûlé en caramélisant, donnant un goût amer au bouillon."),
  plat('Velouté de volaille', 'potage', N_MOYEN, TOUTES_SAISONS, 2, null,
    "Un velouté pâle et soyeux, lié à la crème fraîche.",
    "La liaison à la crème est parfaite, le velouté nappe la cuillère.",
    'Le velouté est un peu trop épais, presque une purée.',
    "La crème a tranché en bouillant, laissant des grumeaux disgracieux."),
  plat('Bisque de homard', 'potage', N_ARISTO, TOUTES_SAISONS, 5, "Un champagne brut",
    'Une bisque orangée, riche et parfumée de cognac flambé.',
    "La bisque, d'un rouge profond, dévoile un parfum iodé somptueux.",
    "La bisque manque un peu de liaison, restant légèrement claire.",
    "Les carapaces ont brûlé en flambant, donnant un goût âcre à toute la bisque."),
  plat('Consommé brunoise', 'potage', N_HAUT, TOUTES_SAISONS, 3, null,
    'Un bouillon clair et doré, parsemé de légumes taillés en dés.',
    "Le consommé est d'une clarté de cristal, signe d'un travail minutieux.",
    "Le consommé reste un peu trouble malgré la clarification.",
    "Le bouillon a bouilli trop fort lors de la clarification et reste trouble."),
  plat('Potage cultivateur', 'potage', N_POP, TOUTES_SAISONS, 1, null,
    'Une soupe épaisse de légumes du potager et de lard fumé.',
    'Tous les légumes du potager se marient dans un bouillon réconfortant.',
    "Les légumes ne sont pas coupés régulièrement, certains restent durs.",
    "Le lard a trop salé tout le potage, le rendant immangeable."),
  plat('Soupe au pistou', 'potage', N_MOYEN, CHAUD, 2, null,
    'Une soupe de légumes d\'été relevée d\'un pistou au basilic.',
    'Le pistou frais relève à merveille cette soupe gorgée de soleil.',
    'Le pistou est un peu trop ail, mais la soupe reste bonne.',
    "Le basilic a noirci en attendant trop longtemps, gâtant le pistou."),
  plat('Velouté Dubarry', 'potage', N_HAUT, FROID, 3, null,
    'Un velouté blanc de chou-fleur, fin et délicatement crémeux.',
    'Le chou-fleur, parfaitement cuit, donne un velouté d\'une finesse rare.',
    "Le velouté garde un léger goût de chou trop prononcé.",
    "Le chou-fleur a trop cuit et dégage une odeur soufrée désagréable."),
  plat('Potage Esaü', 'potage', N_POP, FROID, 1, null,
    'Une purée épaisse de lentilles brunes, parfumée au lard.',
    'Les lentilles fondent en bouche dans un velouté riche et nourrissant.',
    'Le potage est un peu trop épais, presque une purée.',
    "Les lentilles n'ont pas assez trempé et restent dures sous la dent."),
  plat('Bouillon de pot-au-feu', 'potage', N_POP, FROID, 1, null,
    'Un bouillon doré, parsemé de vermicelles fins.',
    'Le bouillon, longuement mijoté, est d\'une richesse et d\'un parfum exquis.',
    'Le bouillon manque un peu de force, ayant trop été allongé.',
    "Le bouillon n'a pas été écumé : il reste gras et trouble."),
  plat('Velouté d\'asperges', 'potage', N_HAUT, CHAUD, 3, "Un riesling sec",
    'Un velouté vert pâle, délicat parfum de jeunes asperges.',
    "Le velouté capture toute la délicatesse des asperges nouvelles.",
    "Les fibres des asperges n'ont pas été bien filtrées.",
    "Les asperges étaient trop vieilles et donnent un goût fibreux et amer."),
  plat('Potage julienne', 'potage', N_POP, TOUTES_SAISONS, 1, null,
    'Un bouillon clair, garni de fins bâtonnets de légumes.',
    'Les légumes, taillés avec soin, restent croquants dans un bouillon léger.',
    "Les légumes sont coupés trop gros, cuisant inégalement.",
    "Les légumes ont trop cuit et se sont délités dans le bouillon."),
  plat('Soupe aux choux', 'potage', N_POP, FROID, 1, null,
    'Une soupe paysanne, épaisse de chou et de lard.',
    'Le chou, longuement mijoté, a pris un goût fondant et savoureux.',
    "La soupe est un peu fade, le lard n'ayant pas assez infusé.",
    "Le chou a trop cuit et dégage une odeur entêtante dans toute la maison."),
  plat('Bisque d\'écrevisses', 'potage', N_ARISTO, CHAUD, 4, "Un meursault",
    'Une bisque rosée, parfumée et finement crémée.',
    "La bisque révèle un parfum d'écrevisse intense et délicat.",
    "La bisque est un peu trop liquide, manquant de liaison.",
    "Les écrevisses n'ont pas été décortiquées à temps et donnent un goût amer."),
  plat('Consommé royal', 'potage', N_HAUT, TOUTES_SAISONS, 3, null,
    'Un bouillon doré garni de fins losanges de royale aux œufs.',
    'La royale, tranchée en losanges délicats, flotte avec élégance.',
    "La royale est un peu trop ferme, presque caoutchouteuse.",
    "La royale n'a pas pris à la cuisson et se délite dans le bouillon."),
  plat('Potage Longchamp', 'potage', N_HAUT, CHAUD, 2, null,
    'Un velouté de petits pois relevé de chiffonnade d\'oseille.',
    "L'oseille apporte une pointe d'acidité qui réveille tout le potage.",
    "L'oseille est un peu trop présente et domine le potage.",
    "L'oseille a trop cuit et donne au potage une couleur grisâtre peu appétissante."),
  plat('Velouté de champignons', 'potage', N_MOYEN, FROID, 2, null,
    'Un velouté beige clair, parfumé de champignons de Paris.',
    'Les champignons embaument le velouté d\'un parfum boisé délicat.',
    'Le velouté est un peu trop liquide.',
    "Les champignons n'étaient plus frais et donnent un goût terreux désagréable."),
  plat('Garbure paysanne', 'potage', N_POP, FROID, 1, null,
    'Une soupe épaisse de chou, haricots et confit d\'oie.',
    'Le confit fond dans la soupe, lui donnant une richesse incomparable.',
    'La soupe est un peu trop grasse, mais réconfortante.',
    "Les haricots n'ont pas assez trempé et restent durs sous la dent."),

  // ── HORS_D_OEUVRE (15) ──────────────────────────────────────────────
  plat('Terrine de campagne', 'hors_d_oeuvre', N_POP, TOUTES_SAISONS, 2, "Un vin rouge de pays",
    'Une tranche épaisse, parsemée de pistaches, servie avec des cornichons.',
    "La terrine, parfaitement assaisonnée, fond presque sous la dent.",
    'La terrine est un peu sèche mais le goût reste plaisant.',
    "La terrine n'a pas assez cuit et reste rosée et collante au centre."),
  plat('Escargots de Bourgogne', 'hors_d_oeuvre', N_HAUT, FROID, 3, "Un chablis",
    "Des coquilles fumantes, gorgées de beurre persillé.",
    'Le beurre persillé, fondu à point, embaume toute la table.',
    "L'ail est un peu trop présent dans le beurre.",
    "Le beurre a brûlé au four et donne un goût âcre aux escargots."),
  plat('Œufs mayonnaise', 'hors_d_oeuvre', N_POP, TOUTES_SAISONS, 1, null,
    'Des œufs durs nappés d\'une mayonnaise jaune pâle.',
    "La mayonnaise, montée à la perfection, nappe délicatement chaque œuf.",
    'La mayonnaise est un peu trop liquide.',
    "La mayonnaise a tranché en la montant, formant une sauce grumeleuse."),
  plat('Salade niçoise', 'hors_d_oeuvre', N_MOYEN, CHAUD, 1, null,
    'Tomates, anchois et olives noires, arrosés d\'une huile fruitée.',
    "Tous les ingrédients, d'une fraîcheur parfaite, chantent l'été.",
    'Les tomates manquaient un peu de maturité.',
    "Les anchois étaient trop salés et dominent toute la salade."),
  plat('Rillettes du Mans', 'hors_d_oeuvre', N_POP, TOUTES_SAISONS, 1, null,
    'Une terrine grasse et filandreuse, à tartiner sur du pain de campagne.',
    'Les rillettes, longuement confites, fondent en bouche divinement.',
    'Les rillettes sont un peu trop salées.',
    "Les rillettes n'ont pas assez confit et restent fibreuses et sèches."),
  plat('Jambon de Bayonne', 'hors_d_oeuvre', N_MOYEN, TOUTES_SAISONS, 1, "Un vin blanc du Jurançon",
    'De fines tranches rosées, disposées en éventail.',
    'Le jambon, finement tranché, révèle un parfum salé et délicat.',
    'Les tranches sont coupées un peu trop épaisses.',
    "Le jambon était trop sec et casse au lieu de se trancher finement."),
  plat('Anchois marinés', 'hors_d_oeuvre', N_POP, CHAUD, 1, null,
    'Des filets argentés, marinés dans l\'huile et le vinaigre.',
    'Les anchois, bien dessalés, offrent un équilibre parfait entre sel et acidité.',
    'Les anchois restent un peu trop salés.',
    "Les anchois n'ont pas été dessalés et sont immangeables."),
  plat('Asperges vinaigrette', 'hors_d_oeuvre', N_HAUT, CHAUD, 2, null,
    'De belles asperges blanches, nappées d\'une vinaigrette moutardée.',
    'Les asperges, cuites al dente, sont d\'une tendreté parfaite.',
    'Les asperges sont un peu trop cuites, légèrement molles.',
    "Les asperges n'ont pas été épluchées et restent fibreuses et amères."),
  plat('Pâté en croûte', 'hors_d_oeuvre', N_HAUT, FROID, 4, "Un vin rouge léger",
    'Une croûte dorée renferme une farce fine entourée de gelée.',
    'La croûte, dorée et croustillante, enveloppe une farce d\'une finesse rare.',
    "La gelée n'a pas bien pris et reste un peu liquide.",
    "La croûte s'est fendue à la cuisson, laissant échapper toute la farce."),
  plat('Crudités du potager', 'hors_d_oeuvre', N_POP, CHAUD, 1, null,
    'Radis, carottes râpées et concombre, frais cueillis du jardin.',
    'Les légumes, d\'une fraîcheur croquante, ravissent par leur simplicité.',
    'Les légumes manquent un peu de fraîcheur.',
    "Les légumes étaient flétris et sans saveur."),
  plat('Œufs en gelée', 'hors_d_oeuvre', N_HAUT, FROID, 3, null,
    'Un œuf poché, suspendu dans une gelée claire et brillante.',
    'La gelée, limpide comme du cristal, sublime l\'œuf poché parfait.',
    'La gelée est un peu trouble.',
    "L'œuf n'était pas assez poché et coule en perçant la gelée."),
  plat('Melon au porto', 'hors_d_oeuvre', N_HAUT, CHAUD, 1, "Un porto blanc",
    'Une moitié de melon évidée, arrosée d\'un trait de porto.',
    'Le melon, parfaitement mûr, se marie à merveille avec le porto sucré.',
    'Le melon manque un peu de maturité.',
    "Le melon n'était pas mûr et reste fade malgré le porto."),
  plat('Harengs pommes à l\'huile', 'hors_d_oeuvre', N_POP, FROID, 1, null,
    'Des filets de hareng fumé, accompagnés de pommes de terre tièdes.',
    'Le hareng, parfaitement fumé, se marie à la perfection avec les pommes tièdes.',
    'Le hareng est un peu trop salé.',
    "Le hareng n'a pas été dessalé et domine tout le plat de son amertume."),
  plat('Salade de museau', 'hors_d_oeuvre', N_POP, FROID, 1, null,
    'Des lamelles de museau de bœuf, relevées d\'une vinaigrette à l\'échalote.',
    'La vinaigrette à l\'échalote relève parfaitement la tendreté du museau.',
    'La vinaigrette manque un peu de piquant.',
    "Le museau n'a pas été assez attendri et reste caoutchouteux."),
  plat('Tartelettes aux champignons', 'hors_d_oeuvre', N_HAUT, FROID, 3, null,
    'De petites tartelettes croustillantes, garnies de champignons à la crème.',
    'La pâte, fine et croustillante, soutient une garniture délicatement crémée.',
    'La pâte est un peu trop épaisse.',
    "La pâte n'a pas cuit à blanc et reste détrempée par la garniture."),

  // ── POISSON (20) ────────────────────────────────────────────────────
  plat('Sole meunière', 'poisson', N_HAUT, TOUTES_SAISONS, 3, "Un chablis",
    'Une sole dorée au beurre, parsemée de persil frais.',
    'La chair, nacrée et fondante, se détache parfaitement de l\'arête.',
    'La sole est un peu trop cuite sur les bords.',
    "Le beurre a brûlé dans la poêle, donnant un goût âcre au poisson."),
  plat('Truite aux amandes', 'poisson', N_MOYEN, TOUTES_SAISONS, 2, "Un sancerre",
    'Une truite dorée, couronnée d\'amandes effilées grillées.',
    'Les amandes grillées apportent un croquant parfait à la chair fondante.',
    'Les amandes sont un peu trop pâles, pas assez torréfiées.',
    "Les amandes ont brûlé dans le beurre, gâtant tout le plat de leur amertume."),
  plat('Brochet sauce beurre blanc', 'poisson', N_HAUT, TOUTES_SAISONS, 4, "Un muscadet",
    'Un brochet poché, nappé d\'une sauce blonde et mousseuse.',
    'Le beurre blanc, monté à la perfection, est soyeux et acidulé à souhait.',
    'La sauce est un peu trop liquide, ayant tranché légèrement.',
    "La sauce a complètement tranché et se sépare en une bouillie huileuse."),
  plat('Turbot poché', 'poisson', N_ARISTO, TOUTES_SAISONS, 4, "Un champagne",
    'Un turbot entier, poché au court-bouillon, présenté sur argent.',
    'La chair, d\'une blancheur et d\'une fermeté royales, est un délice.',
    'Le turbot est un peu trop cuit, légèrement sec.',
    "Le turbot a trop poché et se délite en morceaux dans le court-bouillon."),
  plat('Bar grillé au fenouil', 'poisson', N_HAUT, CHAUD, 3, "Un vin blanc de Provence",
    'Un bar entier, grillé sur un lit de fenouil flambé au pastis.',
    'Le fenouil flambé parfume délicatement une chair grillée à la perfection.',
    'Le bar est un peu trop grillé d\'un côté.',
    "Le fenouil a trop flambé et a brûlé la peau du bar."),
  plat('Raie au beurre noir', 'poisson', N_MOYEN, FROID, 2, null,
    'Une aile de raie nappée d\'un beurre noisette et de câpres.',
    'Le beurre noisette, juste avant de noircir, sublime la raie tendre.',
    'Le beurre est un peu trop clair, pas assez noisette.',
    "Le beurre a réellement noirci et brûlé, rendant la sauce amère."),
  plat('Morue à la bénédictine', 'poisson', N_POP, FROID, 2, null,
    'Une morue dessalée, gratinée avec pommes de terre et crème.',
    'La morue, parfaitement dessalée, fond dans une crème délicate.',
    'La morue est encore un peu salée.',
    "La morue n'a pas assez dessalé et reste immangeable de sel."),
  plat('Quenelles de brochet', 'poisson', N_HAUT, TOUTES_SAISONS, 4, "Un vin blanc de Bourgogne",
    'De légères quenelles nappées d\'une sauce Nantua rosée.',
    'Les quenelles, aériennes et mousseuses, fondent littéralement en bouche.',
    'Les quenelles sont un peu denses, manquant de légèreté.',
    "Les quenelles se sont défaites à la cuisson dans le bouillon."),
  plat('Matelote d\'anguille', 'poisson', N_POP, FROID, 2, "Un vin rouge léger",
    'Un ragoût d\'anguille mijoté au vin rouge et aux oignons.',
    'L\'anguille, fondante, s\'imprègne merveilleusement du vin rouge.',
    'L\'anguille est un peu trop cuite, légèrement filandreuse.',
    "L'anguille n'a pas été bien dépouillée et garde un goût terreux."),
  plat('Saumon à l\'oseille', 'poisson', N_HAUT, CHAUD, 3, "Un pouilly-fumé",
    'Un pavé de saumon rosé, nappé d\'une sauce crémeuse à l\'oseille.',
    'L\'acidité de l\'oseille équilibre à merveille le gras du saumon.',
    'La sauce est un peu trop acide.',
    "Le saumon a trop cuit et devient sec et filandreux."),
  plat('Maquereaux au vin blanc', 'poisson', N_POP, CHAUD, 1, null,
    'Des maquereaux marinés, servis froids dans une gelée légère.',
    'La marinade au vin blanc parfume délicatement une chair ferme.',
    'Les maquereaux sont un peu trop marinés, légèrement acides.',
    "Les maquereaux n'étaient pas frais et dégagent une odeur forte."),
  plat('Cabillaud à la dieppoise', 'poisson', N_MOYEN, FROID, 2, "Un vin blanc normand",
    'Un dos de cabillaud nappé d\'une sauce crémeuse aux moules.',
    'Les moules et les crevettes apportent une richesse iodée parfaite.',
    'La sauce manque un peu de liaison.',
    "Les moules n'ont pas été triées et certaines étaient encore fermées et toxiques."),
  plat('Homard thermidor', 'poisson', N_ARISTO, TOUTES_SAISONS, 5, "Un champagne millésimé",
    'Un homard gratiné dans sa carapace, nappé d\'une sauce moutardée.',
    'La chair du homard, généreuse et juteuse, se marie à la perfection avec la sauce.',
    'Le homard est un peu trop cuit, légèrement caoutchouteux.',
    "Le homard a été trop cuit dès le départ et la chair devient du caoutchouc."),
  plat('Langouste grillée', 'poisson', N_ARISTO, CHAUD, 4, "Un champagne",
    'Une langouste fendue en deux, grillée et nappée de beurre fondu.',
    'La chair, ferme et sucrée, est sublimée par le beurre fondu.',
    'La langouste est un peu trop grillée sur les bords.',
    "La langouste a brûlé sur le gril et le beurre a noirci."),
  plat('Moules marinières', 'poisson', N_POP, TOUTES_SAISONS, 1, "Un muscadet",
    'Une marmite fumante de moules ouvertes au vin blanc et persil.',
    'Les moules, toutes bien ouvertes, baignent dans un bouillon parfumé.',
    'Quelques moules ne se sont pas ouvertes.',
    "Plusieurs moules n'étaient pas fraîches et gâtent tout le plat."),
  plat('Huîtres de Marennes', 'poisson', N_HAUT, FROID, 1, "Un chablis",
    'Une douzaine d\'huîtres fraîchement ouvertes, sur lit de glace pilée.',
    'Les huîtres, iodées et charnues, sont d\'une fraîcheur exceptionnelle.',
    'Quelques huîtres sont un peu maigres pour la saison.',
    "Une huître mal ouverte contient des éclats de coquille."),
  plat('Écrevisses à la nage', 'poisson', N_ARISTO, CHAUD, 3, "Un vin blanc sec",
    'Des écrevisses rougies, baignant dans un court-bouillon aromatique.',
    'Le court-bouillon, riche en aromates, parfume délicatement les écrevisses.',
    'Les écrevisses sont un peu trop cuites.',
    "Les écrevisses n'ont pas été châtrées et restent amères."),
  plat('Brandade de morue', 'poisson', N_POP, FROID, 2, "Un vin blanc de Provence",
    'Une purée onctueuse de morue, huile d\'olive et lait.',
    'La brandade, montée comme une mayonnaise, est d\'une onctuosité parfaite.',
    'La brandade est un peu trop liquide.',
    "L'huile a tranché en montant la brandade, la rendant grasse et granuleuse."),
  plat('Dorade rôtie', 'poisson', N_MOYEN, CHAUD, 2, null,
    'Une dorade entière rôtie au four, sur lit de tomates et d\'herbes.',
    'La peau croustillante cache une chair fondante parfaitement assaisonnée.',
    'La dorade est un peu trop cuite côté arête.',
    "La dorade n'a pas été écaillée correctement, rendant la peau immangeable."),
  plat('Colin sauce normande', 'poisson', N_HAUT, FROID, 3, "Un cidre brut",
    'Un filet de colin nappé d\'une sauce crémeuse au cidre et aux pommes.',
    'La sauce au cidre, délicatement acidulée, sublime la chair délicate du colin.',
    'La sauce manque un peu d\'acidité.',
    "Le cidre n'a pas réduit suffisamment et la sauce reste trop liquide."),

  // ── VIANDE (25) ─────────────────────────────────────────────────────
  plat('Pot-au-feu du dimanche', 'viande', N_POP, FROID, 1, "Un vin rouge ordinaire",
    'Un plateau de bœuf bouilli, entouré de légumes fondants.',
    'La viande, longuement mijotée, se détache littéralement à la fourchette.',
    'La viande est un peu ferme par endroits.',
    "La viande n'a pas assez mijoté et reste dure et fibreuse."),
  plat('Blanquette de veau', 'viande', N_MOYEN, FROID, 3, "Un vin blanc sec",
    'Des morceaux de veau nappés d\'une sauce blanche crémeuse au citron.',
    'La sauce, liée à la perfection, enrobe une viande d\'une tendreté exquise.',
    'La sauce a légèrement tranché en la liant.',
    "La sauce a complètement tranché et se sépare en une bouillie inégale."),
  plat('Daube provençale', 'viande', N_MOYEN, FROID, 2, "Un côtes-du-rhône",
    'Un ragoût de bœuf mijoté de longues heures au vin rouge et aux olives.',
    'La viande, fondante après des heures de mijotage, embaume le thym et l\'olive.',
    'La sauce est un peu trop liquide.',
    "La daube n'a pas assez mijoté et la viande reste coriace."),
  plat('Civet de bœuf', 'viande', N_POP, FROID, 2, "Un vin rouge corsé",
    'Un ragoût brun foncé, lié au sang et relevé de lardons.',
    'Le civet, riche et corsé, a une sauce d\'un brun profond et velouté.',
    'La sauce manque un peu de liaison.',
    "Le sang a tranché en cuisant, donnant une sauce granuleuse et amère."),
  plat('Rôti de bœuf', 'viande', N_HAUT, TOUTES_SAISONS, 2, "Un bordeaux",
    'Un beau rôti rosé, entouré de son jus corsé.',
    'La viande, saignante et tendre, repose dans un jus d\'une richesse parfaite.',
    'Le rôti est un peu trop cuit, plus à point que saignant.',
    "Le rôti a trop cuit et devient sec et gris à cœur."),
  plat('Gigot d\'agneau', 'viande', N_HAUT, CHAUD, 2, "Un saint-émilion",
    'Un gigot rosé, piqué d\'ail et parfumé de romarin.',
    'L\'ail et le romarin parfument délicatement une chair rosée et tendre.',
    'Le gigot est un peu trop cuit.',
    "Le gigot n'a pas reposé après cuisson et tout le jus s'échappe en le tranchant."),
  plat('Côte de porc grillée', 'viande', N_POP, TOUTES_SAISONS, 1, null,
    'Une côte épaisse, grillée et caramélisée sur les bords.',
    'La côte, grillée à point, reste juteuse sous une croûte caramélisée.',
    'La côte est un peu sèche sur les bords.',
    "La côte a trop grillé et devient sèche et dure comme du carton."),
  plat('Choucroute garnie', 'viande', N_POP, FROID, 2, "Une bière blonde",
    'Un monticule de chou fermenté, entouré de saucisses et de lard.',
    'Le chou, longuement mijoté au vin blanc, est parfaitement équilibré.',
    'Le chou est un peu trop acide.',
    "Le chou n'a pas été rincé et reste agressivement acide."),
  plat('Tournedos Rossini', 'viande', N_ARISTO, TOUTES_SAISONS, 5, "Un saint-julien",
    'Un médaillon de bœuf surmonté d\'une tranche de foie gras poêlé.',
    'Le foie gras, fondant, se marie à la perfection avec le bœuf saignant.',
    'Le foie gras est un peu trop cuit, légèrement sec.',
    "Le foie gras a totalement fondu à la poêle et disparaît dans la graisse."),
  plat('Navarin d\'agneau', 'viande', N_MOYEN, CHAUD, 2, "Un vin rouge léger",
    'Un ragoût d\'agneau printanier, entouré de petits légumes nouveaux.',
    'Les légumes nouveaux, juste cuits, accompagnent une viande fondante.',
    'Les légumes sont un peu trop cuits.',
    "Les légumes ont trop cuit et se sont délités dans la sauce."),
  plat('Bœuf bourguignon', 'viande', N_MOYEN, FROID, 3, "Un bourgogne",
    'Un ragoût brun foncé, mijoté au vin rouge avec champignons et lardons.',
    'La viande, fondante, baigne dans une sauce d\'un brun profond et velouté.',
    'La sauce manque un peu de réduction.',
    "Le vin n'a pas réduit suffisamment et la sauce reste acide et liquide."),
  plat('Carbonade flamande', 'viande', N_POP, FROID, 2, "Une bière brune",
    'Un ragoût de bœuf mijoté à la bière brune et au pain d\'épice.',
    'La bière et le pain d\'épice donnent une sauce sucrée-salée remarquable.',
    'La sauce est un peu trop sucrée.',
    "La bière n'a pas réduit et donne une amertume désagréable à la sauce."),
  plat('Ragoût de mouton', 'viande', N_POP, FROID, 1, null,
    'Un ragoût roboratif de mouton et de pommes de terre.',
    'Le mouton, longuement mijoté, est d\'une tendreté remarquable.',
    'Le mouton garde un léger goût de suint.',
    "Le mouton n'a pas été dégraissé et la sauce devient écœurante."),
  plat('Côtelettes d\'agneau', 'viande', N_HAUT, CHAUD, 2, "Un médoc",
    'De petites côtelettes grillées, en couronne, parées de papillotes.',
    'Les côtelettes, grillées juste à point, restent roses et juteuses.',
    'Les côtelettes sont un peu trop cuites.',
    "Les côtelettes ont trop grillé et sont sèches comme de la semelle."),
  plat('Filet de bœuf', 'viande', N_ARISTO, TOUTES_SAISONS, 3, "Un pomerol",
    'Un filet épais, saisi à la poêle, nappé d\'un jus court.',
    'Le filet, saisi à la perfection, est fondant à souhait sous la dent.',
    'Le filet est un peu trop cuit.',
    "Le filet a trop cuit à cœur et perd toute sa tendreté."),
  plat('Rôti de porc aux pruneaux', 'viande', N_MOYEN, FROID, 2, "Un vin rouge fruité",
    'Un rôti de porc farci de pruneaux, nappé d\'un jus sucré-salé.',
    'Les pruneaux, fondus dans le jus, apportent une note sucrée délicieuse.',
    'Le jus est un peu trop sucré.',
    "Le rôti a trop cuit et les pruneaux ont brûlé au fond du plat."),
  plat('Jarret de veau braisé', 'viande', N_MOYEN, FROID, 3, "Un vin blanc corsé",
    'Un jarret entier, braisé des heures, à la moelle fondante.',
    'La viande, braisée longuement, se détache de l\'os toute seule.',
    'Le jarret est un peu sec en surface.',
    "Le jarret n'a pas assez braisé et la viande reste collée à l'os."),
  plat('Pieds de cochon', 'viande', N_POP, FROID, 2, null,
    'Des pieds de cochon panés et grillés, croustillants et gélatineux.',
    'La panure croustillante cache une chair gélatineuse fondante.',
    'La panure est un peu trop pâle.',
    "Les pieds n'ont pas assez cuit et restent caoutchouteux sous la panure."),
  plat('Andouillette grillée', 'viande', N_POP, TOUTES_SAISONS, 2, "Un muscadet",
    'Une andouillette grillée, accompagnée d\'une moutarde forte.',
    'L\'andouillette, grillée à point, libère un parfum corsé et authentique.',
    'L\'andouillette est un peu trop grillée d\'un côté.',
    "L'andouillette a éclaté sur le gril, libérant une odeur forte et désagréable."),
  plat('Tripes à la mode de Caen', 'viande', N_POP, FROID, 2, "Un cidre",
    'Un ragoût de tripes mijoté au cidre avec carottes et poireaux.',
    'Les tripes, mijotées des heures, sont d\'une tendreté et d\'un parfum remarquables.',
    'Les tripes ont un léger goût trop prononcé.',
    "Les tripes n'ont pas été assez nettoyées et gardent une odeur entêtante."),
  plat('Escalope de veau milanaise', 'viande', N_MOYEN, TOUTES_SAISONS, 2, "Un chianti",
    'Une escalope panée et dorée, garnie de spaghettis tomatés.',
    'La panure, dorée et croustillante, enrobe une chair tendre à souhait.',
    'La panure est un peu trop pâle.',
    "L'escalope a trop cuit dans l'huile et la panure brûle, donnant un goût âcre."),
  plat('Médaillons de porc', 'viande', N_POP, TOUTES_SAISONS, 1, null,
    'De petits médaillons poêlés, nappés d\'une sauce moutardée.',
    'La sauce moutardée relève à merveille une viande tendre et juteuse.',
    'La sauce manque un peu de liaison.',
    "Les médaillons ont trop cuit et deviennent secs et caoutchouteux."),
  plat('Hachis Parmentier', 'viande', N_POP, FROID, 1, null,
    'Une purée dorée au four, cachant une viande hachée mijotée.',
    'Le gratin doré cache une purée onctueuse et une viande parfaitement relevée.',
    'Le gratin manque un peu de couleur.',
    "La purée n'a pas été assez battue et reste grumeleuse sous le gratin."),
  plat('Longe de veau rôtie', 'viande', N_HAUT, CHAUD, 3, "Un vin blanc de Bourgogne",
    'Une longe rosée, rôtie entière et tranchée en fines tranches.',
    'La longe, rosée à cœur, est d\'une tendreté et d\'une finesse exquises.',
    'La longe est un peu trop cuite.',
    "La longe a trop cuit et devient sèche et filandreuse."),
  plat('Canard rôti aux navets', 'viande', N_HAUT, FROID, 3, "Un pinot noir",
    'Un canard entier rôti, entouré de petits navets glacés.',
    'La peau croustillante cache une chair juteuse et parfumée.',
    'La peau n\'a pas assez croustillé.',
    "Le canard a trop cuit et la chair devient sèche et fibreuse."),

  // ── VOLAILLE (15) ───────────────────────────────────────────────────
  plat('Poularde au pot', 'volaille', N_HAUT, FROID, 2, "Un vin blanc sec",
    'Une poularde entière, pochée dans son bouillon avec légumes.',
    'La poularde, fondante, se détache de l\'os avec une facilité royale.',
    'La poularde est un peu trop cuite par endroits.',
    "La poularde n'a pas été bridée et se déforme à la cuisson."),
  plat('Poulet rôti', 'volaille', N_POP, TOUTES_SAISONS, 1, null,
    'Un poulet doré, croustillant, parfumé au thym.',
    'La peau, dorée et croustillante, cache une chair juteuse à souhait.',
    'La peau n\'a pas assez doré.',
    "Le poulet a trop cuit et la chair devient sèche et filandreuse."),
  plat('Coq au vin', 'volaille', N_MOYEN, FROID, 3, "Un bourgogne rouge",
    'Un ragoût de coq mijoté au vin rouge, lardons et champignons.',
    'Le coq, mijoté des heures, est fondant dans une sauce riche et corsée.',
    'La sauce manque un peu de réduction.',
    "Le vin n'a pas assez réduit et la sauce reste âpre et trop alcoolisée."),
  plat('Canard à l\'orange', 'volaille', N_HAUT, FROID, 3, "Un vin blanc moelleux",
    'Un magret tranché, nappé d\'une sauce orangée aigre-douce.',
    'La sauce à l\'orange, parfaitement équilibrée, sublime le canard rosé.',
    'La sauce est un peu trop sucrée.',
    "Le sucre a caramélisé trop fort et la sauce devient âcre et brûlée."),
  plat('Pintade rôtie', 'volaille', N_HAUT, FROID, 2, "Un vin rouge léger",
    'Une pintade entière, rôtie et bardée de lard.',
    'Le lard, fondu pendant la cuisson, garde la chair délicate et juteuse.',
    'La pintade est un peu sèche.',
    "La pintade n'a pas été bardée et la chair, maigre, devient sèche."),
  plat('Suprême de volaille', 'volaille', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Un blanc de volaille poché, nappé d\'une sauce suprême crémeuse.',
    'La sauce, soyeuse et délicate, enrobe une chair d\'une tendreté parfaite.',
    'La sauce manque un peu de liaison.',
    "Le blanc a trop poché et devient sec et caoutchouteux."),
  plat('Dinde farcie', 'volaille', N_HAUT, FROID, 3, "Un vin rouge fruité",
    'Une dinde entière, farcie de marrons et de chair à saucisse.',
    'La farce aux marrons parfume délicieusement une chair moelleuse.',
    'La farce est un peu trop sèche.',
    "La dinde n'a pas assez cuit au centre, la farce restant crue."),
  plat('Oie de la Saint-Martin', 'volaille', N_ARISTO, FROID, 4, "Un vin rouge corsé",
    'Une oie rôtie entière, dorée et craquante.',
    'La graisse d\'oie, dorée et croustillante, parfume toute la pièce.',
    'L\'oie est un peu trop grasse.',
    "L'oie n'a pas été dégraissée et la sauce devient écœurante."),
  plat('Poule au riz', 'volaille', N_POP, FROID, 1, null,
    'Une poule pochée, servie sur un lit de riz nappé de bouillon.',
    'La poule, longuement pochée, est fondante et parfume tout le riz.',
    'Le riz est un peu trop cuit.',
    "Le riz a trop absorbé le bouillon et devient une bouillie collante."),
  plat('Magret de canard', 'volaille', N_HAUT, TOUTES_SAISONS, 3, "Un cahors",
    'Un magret saisi, peau croustillante, chair rosée à cœur.',
    'La peau, croustillante et dorée, cache une chair rosée et juteuse.',
    'Le magret est un peu trop cuit.',
    "La peau n'a pas assez rendu sa graisse et reste molle et caoutchouteuse."),
  plat('Chapon de Noël', 'volaille', N_ARISTO, FROID, 4, "Un champagne",
    'Un chapon doré, farci de truffes sous la peau.',
    'Les truffes, glissées sous la peau, parfument la chair tout du long.',
    'La farce aux truffes est un peu discrète.',
    "Le chapon n'a pas reposé et toute la farce truffée s'échappe en le tranchant."),
  plat('Fricassée de poulet', 'volaille', N_POP, TOUTES_SAISONS, 2, null,
    'Des morceaux de poulet mijotés dans une sauce blanche aux champignons.',
    'La sauce, légère et crémeuse, enrobe une viande tendre à souhait.',
    'La sauce manque un peu de liaison.',
    "La sauce a tranché en cuisant et se sépare désagréablement."),
  plat('Poularde demi-deuil', 'volaille', N_ARISTO, FROID, 4, "Un vin blanc de Bourgogne",
    'Une poularde pochée, truffe glissée sous la peau, nappée de crème.',
    'La truffe, glissée sous la peau, parfume délicatement toute la volaille.',
    'La sauce manque un peu de truffe.',
    "La truffe a été coupée trop tôt et a perdu tout son parfum."),
  plat('Caneton aux navets', 'volaille', N_HAUT, FROID, 3, "Un pinot noir",
    'Un caneton rôti, entouré de navets caramélisés au sucre.',
    'Les navets, caramélisés à point, équilibrent à merveille le gras du canard.',
    'Les navets sont un peu trop sucrés.',
    "Les navets ont brûlé en caramélisant et donnent un goût amer au plat."),
  plat('Volaille en gelée', 'volaille', N_HAUT, CHAUD, 3, null,
    'Des morceaux de volaille pochée, pris dans une gelée claire et estivale.',
    'La gelée, limpide et fraîche, est du plus bel effet sur la table d\'été.',
    'La gelée est un peu trouble.',
    "La gelée n'a pas pris et tout le plat se transforme en bouillon."),

  // ── GIBIER (10) ─────────────────────────────────────────────────────
  plat('Civet de lièvre', 'gibier', N_HAUT, FROID, 4, "Un vin rouge corsé",
    'Un ragoût brun foncé, lié au sang du lièvre, intensément parfumé.',
    'Le civet, mariné puis mijoté des heures, atteint une profondeur de goût rare.',
    'La sauce manque un peu de liaison.',
    "Le sang a tranché en cuisant trop vite, rendant la sauce granuleuse et amère."),
  plat('Faisan rôti', 'gibier', N_ARISTO, FROID, 4, "Un vin rouge de Bourgogne",
    'Un faisan entier, paré de ses plumes de queue, rôti et bardé.',
    'Le faisan, bardé avec soin, garde une chair étonnamment moelleuse.',
    'Le faisan est un peu sec.',
    "Le faisan n'a pas été bardé et sa chair maigre devient sèche comme du bois."),
  plat('Perdrix aux choux', 'gibier', N_HAUT, FROID, 3, "Un vin rouge léger",
    'Des perdrix braisées sur un lit de chou fondant au lard.',
    'Le chou, imprégné du jus des perdrix, est d\'un fondant remarquable.',
    'Le chou est un peu trop cuit.',
    "Le chou a trop mijoté et perd toute sa texture, devenant une bouillie."),
  plat('Marcassin en sauce', 'gibier', N_MOYEN, FROID, 3, "Un vin rouge corsé",
    'Un ragoût de marcassin mariné, mijoté au vin et aux baies de genièvre.',
    'Le genièvre relève à merveille une chair jeune et tendre.',
    'La marinade n\'a pas suffisamment infusé.',
    "Le marcassin n'a pas mariné assez longtemps et garde un goût sauvage prononcé."),
  plat('Chevreuil grand veneur', 'gibier', N_ARISTO, FROID, 5, "Un vin rouge puissant",
    'Un filet de chevreuil nappé d\'une sauce poivrée à la gelée de groseille.',
    'La sauce poivrée, relevée de groseille, sublime une chair fine et délicate.',
    'La sauce est un peu trop poivrée.',
    "Le filet a trop cuit et perd toute la finesse propre au chevreuil."),
  plat('Lapin de garenne', 'gibier', N_POP, TOUTES_SAISONS, 2, "Un vin rouge léger",
    'Un lapin mijoté à la moutarde, accompagné de pruneaux.',
    'La moutarde et les pruneaux s\'équilibrent parfaitement autour d\'une chair tendre.',
    'La sauce est un peu trop moutardée.',
    "Le lapin a trop mijoté et la chair se délite complètement dans la sauce."),
  plat('Bécasse rôtie', 'gibier', N_ARISTO, FROID, 5, "Un vin rouge fin",
    'Une bécasse entière, rôtie avec ses entrailles sur canapé.',
    'La bécasse, cuisinée selon la tradition, révèle des saveurs d\'une rare intensité.',
    'La cuisson est un peu inégale.',
    "La bécasse a trop cuit et perd tout l'intérêt de sa cuisson traditionnelle."),
  plat('Sanglier aux marrons', 'gibier', N_HAUT, FROID, 4, "Un vin rouge corsé",
    'Un ragoût de sanglier mariné, mijoté avec des marrons entiers.',
    'Les marrons, fondants, adoucissent à merveille la force du sanglier.',
    'Les marrons sont un peu trop fermes.',
    "Le sanglier n'a pas mariné assez longtemps et garde un goût fort et musqué."),
  plat('Caille sur canapé', 'gibier', N_HAUT, FROID, 3, "Un vin rouge léger",
    'De petites cailles rôties, posées sur un canapé de pain doré.',
    'Les cailles, rôties à la perfection, restent juteuses sous une peau dorée.',
    'Les cailles sont un peu trop cuites.',
    "Les cailles ont trop cuit et leur chair délicate devient sèche."),
  plat('Lièvre à la royale', 'gibier', N_ARISTO, FROID, 5, "Un vin rouge de garde",
    'Un lièvre entier désossé, farci et mijoté des heures au vin et au foie gras.',
    'Le lièvre à la royale, ultime sommet de l\'art culinaire, est d\'une richesse inégalée.',
    'La sauce manque un peu de liaison au sang.',
    "Le désossage a été mal réalisé et le lièvre se déstructure complètement à la cuisson."),

  // ── ABATS (8) ───────────────────────────────────────────────────────
  plat('Foie de veau poêlé', 'abats', N_MOYEN, TOUTES_SAISONS, 2, "Un vin rouge léger",
    'Des tranches de foie rosées, poêlées rapidement avec des oignons.',
    'Le foie, saisi juste à point, reste rosé et fondant à cœur.',
    'Le foie est un peu trop cuit.',
    "Le foie a trop cuit et devient caoutchouteux et amer."),
  plat('Rognons à la moutarde', 'abats', N_POP, TOUTES_SAISONS, 2, "Un vin rouge corsé",
    'Des rognons sautés, nappés d\'une sauce crémeuse à la moutarde.',
    'La moutarde relève à merveille des rognons tendres et parfaitement déveinés.',
    'Les rognons n\'ont pas été parfaitement déveinés.',
    "Les rognons n'ont pas été déveinés et gardent un goût d'urine prononcé."),
  plat('Ris de veau braisé', 'abats', N_ARISTO, TOUTES_SAISONS, 4, "Un vin blanc de Bourgogne",
    'Des ris de veau braisés, nappés d\'une sauce aux morilles.',
    'Les ris, délicatement braisés, ont la texture fondante la plus exquise qui soit.',
    'Les ris sont un peu fermes.',
    "Les ris n'ont pas été dégorgés et gardent un goût sanguin désagréable."),
  plat('Tête de veau sauce gribiche', 'abats', N_POP, FROID, 2, null,
    'Des morceaux de tête de veau, nappés d\'une sauce gribiche relevée.',
    'La gribiche, vive et relevée, contraste parfaitement avec le fondant de la tête.',
    'La sauce manque un peu de piquant.',
    "La tête n'a pas assez cuit et reste caoutchouteuse sous la sauce."),
  plat('Langue de bœuf sauce piquante', 'abats', N_POP, FROID, 2, "Un vin rouge corsé",
    'Une langue tranchée, nappée d\'une sauce piquante aux câpres.',
    'La langue, longuement mijotée, est tendre comme du beurre sous la sauce relevée.',
    'La sauce manque un peu de piquant.',
    "La langue n'a pas été pelée correctement et garde une peau coriace."),
  plat('Cervelle meunière', 'abats', N_MOYEN, TOUTES_SAISONS, 3, "Un vin blanc sec",
    'Une cervelle pochée puis dorée au beurre, parsemée de câpres.',
    'La cervelle, délicate, fond littéralement sous une croûte dorée parfaite.',
    'La cervelle est un peu trop dorée.',
    "La cervelle n'a pas été dégorgée et se délite complètement à la cuisson."),
  plat('Foie gras de canard mi-cuit', 'abats', N_ARISTO, FROID, 4, "Un sauternes",
    'Une terrine de foie gras, rosée à cœur, servie avec du pain toasté.',
    'Le foie gras, parfaitement mi-cuit, fond délicatement sur la langue.',
    'Le foie gras est un peu trop cuit.',
    "Le foie gras a trop cuit et perd toute sa texture fondante, devenant graisseux."),
  plat('Tripes à la lyonnaise', 'abats', N_POP, FROID, 2, "Un beaujolais",
    'Des tripes sautées avec des oignons dorés et du persil.',
    'Les oignons, caramélisés à point, subliment des tripes parfaitement tendres.',
    'Les oignons sont un peu trop cuits.',
    "Les tripes n'ont pas été assez nettoyées et gardent une odeur entêtante."),

  // ── LEGUME (15) ─────────────────────────────────────────────────────
  plat('Haricots verts au beurre', 'legume', N_TOUS, CHAUD, 1, null,
    'Des haricots verts fins, sautés au beurre noisette.',
    'Les haricots, croquants et brillants de beurre, sont d\'une fraîcheur parfaite.',
    'Les haricots sont un peu trop cuits.',
    "Les haricots ont trop cuit et perdent toute leur couleur et leur croquant."),
  plat('Pommes de terre dauphines', 'legume', N_MOYEN, TOUTES_SAISONS, 2, null,
    'De petites boules dorées et soufflées, croustillantes à l\'extérieur.',
    'Les dauphines, parfaitement soufflées, sont croustillantes dehors et aériennes dedans.',
    'Les dauphines sont un peu trop denses.',
    "La pâte n'a pas assez gonflé à la friture et les dauphines restent denses."),
  plat('Petits pois à la française', 'legume', N_MOYEN, CHAUD, 1, null,
    'Des petits pois braisés à la laitue et aux petits oignons.',
    'Les petits pois, juste cueillis, fondent en bouche avec une douceur rare.',
    'Les petits pois sont un peu trop cuits.',
    "Les petits pois étaient trop vieux et restent durs malgré la cuisson."),
  plat('Choux de Bruxelles', 'legume', N_POP, FROID, 1, null,
    'De petits choux braisés au beurre, légèrement caramélisés.',
    'Les choux, caramélisés juste à point, perdent toute amertume.',
    'Les choux sont un peu trop cuits.',
    "Les choux ont trop cuit et dégagent une odeur soufrée envahissante."),
  plat('Ratatouille niçoise', 'legume', N_POP, CHAUD, 2, null,
    'Un mélange coloré de courgettes, aubergines, poivrons et tomates.',
    'Chaque légume, cuit séparément puis réuni, garde sa texture et sa saveur propre.',
    'Les légumes sont un peu trop fondus ensemble.',
    "Les légumes ont tous cuit ensemble dès le départ et forment une bouillie informe."),
  plat('Gratin dauphinois', 'legume', N_MOYEN, FROID, 2, null,
    'De fines tranches de pommes de terre, gratinées à la crème.',
    'Les pommes de terre, fondantes, sont nappées d\'une crème parfaitement gratinée.',
    'Le gratin est un peu trop liquide.',
    "Les pommes de terre n'ont pas assez cuit et restent dures au centre."),
  plat('Épinards à la crème', 'legume', N_MOYEN, CHAUD, 1, null,
    'Des épinards fondus, liés d\'une crème fraîche épaisse.',
    'Les épinards, juste fondus, gardent leur belle couleur verte intense.',
    'Les épinards ont rendu un peu trop d\'eau.',
    "Les épinards n'ont pas été essorés et la crème devient liquide et fade."),
  plat('Carottes Vichy', 'legume', N_POP, TOUTES_SAISONS, 1, null,
    'Des rondelles de carottes glacées au beurre et au sucre.',
    'Les carottes, glacées à la perfection, brillent d\'un éclat appétissant.',
    'Les carottes sont un peu trop sucrées.',
    "Le sucre a caramélisé trop fort et les carottes prennent un goût amer."),
  plat('Artichauts à la barigoule', 'legume', N_HAUT, CHAUD, 3, "Un vin blanc de Provence",
    'De petits artichauts braisés aux lardons et au vin blanc.',
    'Les artichauts, braisés longuement, sont tendres jusqu\'au cœur.',
    'Les artichauts sont un peu fibreux.',
    "Les artichauts n'ont pas été parés et restent immangeables avec leur foin."),
  plat('Navets glacés', 'legume', N_POP, FROID, 1, null,
    'De petits navets glacés au beurre et au sucre, dorés à point.',
    'Les navets, glacés à la perfection, ont perdu toute leur amertume.',
    'Les navets gardent un peu d\'amertume.',
    "Les navets n'étaient pas de la première fraîcheur et restent amers."),
  plat('Endives braisées', 'legume', N_MOYEN, FROID, 1, null,
    'Des endives braisées au beurre, légèrement caramélisées.',
    'Les endives, caramélisées à point, ont perdu toute amertume excessive.',
    'Les endives gardent un peu d\'amertume.',
    "Les endives ont trop braisé et deviennent amères et filandreuses."),
  plat('Lentilles vertes', 'legume', N_POP, FROID, 1, null,
    'Des lentilles mijotées au lard et aux carottes.',
    'Les lentilles, cuites à point, restent entières et fondantes.',
    'Les lentilles sont un peu trop cuites.',
    "Les lentilles n'ont pas assez trempé et restent dures sous la dent."),
  plat('Purée de pommes de terre', 'legume', N_POP, TOUTES_SAISONS, 1, null,
    'Une purée onctueuse, généreusement beurrée.',
    'La purée, lissée à la fourchette, est d\'une onctuosité remarquable.',
    'La purée est un peu trop liquide.',
    "La purée n'a pas été assez battue et reste grumeleuse et collante."),
  plat('Asperges sauce mousseline', 'legume', N_HAUT, CHAUD, 2, null,
    'De belles asperges blanches, nappées d\'une sauce mousseline légère.',
    'La mousseline, légère et aérienne, sublime des asperges parfaitement cuites.',
    'La sauce manque un peu de légèreté.',
    "La sauce a tranché en la montant et devient une bouillie huileuse."),
  plat("Fonds d'artichaut", 'legume', N_HAUT, CHAUD, 3, null,
    'De grands fonds d\'artichaut, garnis d\'une jardinière de légumes.',
    'Les fonds, tendres et parfaitement parés, soutiennent une garniture délicate.',
    'Les fonds sont un peu fibreux.',
    "Les fonds n'ont pas été parés correctement et restent durs et fibreux."),

  // ── ENTREMETS (12) ──────────────────────────────────────────────────
  plat('Œufs en neige', 'entremets', N_POP, TOUTES_SAISONS, 2, null,
    'De légers nuages de blancs montés, flottant sur une crème anglaise.',
    'Les blancs, montés en neige ferme, flottent comme des nuages sur la crème.',
    'Les blancs sont un peu trop fermes.',
    "Les blancs n'ont pas assez monté et s'effondrent dans la crème."),
  plat('Riz à l\'impératrice', 'entremets', N_HAUT, TOUTES_SAISONS, 3, null,
    'Un riz au lait moulé, parfumé de fruits confits et de kirsch.',
    'Le riz, crémeux et parfumé, se démoule en une forme parfaite.',
    'Le riz est un peu trop ferme.',
    "Le riz n'a pas assez cuit dans le lait et reste granuleux."),
  plat('Soufflé au Grand Marnier', 'entremets', N_ARISTO, TOUTES_SAISONS, 5, "Un sauternes",
    'Un soufflé doré, gonflé bien au-dessus de son moule, parfumé d\'orange.',
    'Le soufflé, gonflé à la perfection, embaume délicieusement le Grand Marnier.',
    'Le soufflé est un peu retombé en sortant du four.',
    "Le soufflé est complètement retombé et ressemble à une crêpe ratée."),
  plat('Blanc-manger', 'entremets', N_MOYEN, CHAUD, 2, null,
    'Une gelée blanche aux amandes, démoulée et tremblotante.',
    'Le blanc-manger, parfaitement pris, tremble délicatement sur l\'assiette.',
    'Le blanc-manger est un peu trop ferme.',
    "Le blanc-manger n'a pas pris et reste liquide au démoulage."),
  plat('Charlotte aux poires', 'entremets', N_HAUT, FROID, 3, null,
    'Des biscuits à la cuillère entourant une mousse aux poires.',
    'La mousse, légère et parfumée, est délicatement entourée de biscuits dorés.',
    'La mousse est un peu trop liquide.',
    "La charlotte n'a pas assez pris au froid et s'effondre au démoulage."),
  plat('Crème caramel', 'entremets', N_POP, TOUTES_SAISONS, 2, null,
    'Une crème onctueuse, nappée d\'un caramel ambré au démoulage.',
    'Le caramel, ambré à la perfection, nappe une crème d\'une finesse exquise.',
    'Le caramel est un peu trop clair.',
    "Le caramel a brûlé dans la casserole et donne un goût âcre à toute la crème."),
  plat('Mousse au chocolat', 'entremets', N_MOYEN, TOUTES_SAISONS, 2, null,
    'Une mousse aérienne, sombre et brillante, en petits pots.',
    'La mousse, montée à la perfection, est aérienne et intensément chocolatée.',
    'La mousse est un peu trop dense.',
    "Les blancs sont retombés en les incorporant et la mousse devient dense et lourde."),
  plat('Île flottante', 'entremets', N_POP, TOUTES_SAISONS, 2, null,
    'Des blancs pochés, flottant sur une crème anglaise nappée de caramel.',
    'Les blancs, pochés délicatement, flottent comme des îles sur la crème dorée.',
    'Les blancs sont un peu trop fermes.',
    "Les blancs n'ont pas été pochés assez longtemps et restent crus au centre."),
  plat('Clafoutis aux cerises', 'entremets', N_POP, CHAUD, 1, null,
    'Une pâte dorée, piquetée de cerises gorgées de jus.',
    'Les cerises, juteuses, éclatent dans une pâte moelleuse et dorée.',
    'Le clafoutis est un peu trop liquide au centre.',
    "Le clafoutis n'a pas assez cuit au centre et reste liquide."),
  plat('Gâteau de semoule', 'entremets', N_POP, TOUTES_SAISONS, 1, null,
    'Un gâteau doré, parfumé de vanille, nappé d\'un coulis de fruits.',
    'La semoule, cuite avec soin, donne un gâteau moelleux et délicatement parfumé.',
    'Le gâteau est un peu trop ferme.',
    "La semoule n'a pas assez cuit dans le lait et reste granuleuse."),
  plat('Beignets de pomme', 'entremets', N_POP, FROID, 1, null,
    'Des rondelles de pomme, enrobées de pâte et frites dorées.',
    'La pâte, légère et croustillante, enrobe des pommes fondantes à souhait.',
    'La pâte est un peu trop épaisse.',
    "L'huile n'était pas assez chaude et les beignets absorbent toute la graisse."),
  plat('Salade de fruits confits', 'entremets', N_HAUT, FROID, 1, "Un vin doux",
    'Un assortiment coloré de fruits confits, arrosé d\'un sirop parfumé.',
    'Les fruits confits, choisis avec soin, offrent un festival de couleurs et de saveurs.',
    'Le sirop est un peu trop sucré.',
    "Les fruits confits étaient trop vieux et ont perdu toute leur saveur."),

  // ── FROMAGE (10) ────────────────────────────────────────────────────
  plat('Brie de Meaux', 'fromage', N_MOYEN, TOUTES_SAISONS, 1, "Un bourgogne rouge",
    'Une large part de brie, croûte fleurie et cœur coulant.',
    'Le brie, affiné à point, coule délicatement sous sa croûte fleurie.',
    'Le brie est un peu trop jeune, encore ferme au centre.',
    "Le brie était trop affiné et dégage une odeur d'ammoniaque envahissante."),
  plat('Camembert affiné', 'fromage', N_POP, FROID, 1, "Un cidre",
    'Un camembert entier, croûte duveteuse, prêt à couler.',
    'Le camembert, affiné juste comme il faut, est crémeux jusqu\'au cœur.',
    'Le camembert est un peu jeune.',
    "Le camembert est trop affiné et son odeur entêtante repousse les convives."),
  plat('Roquefort', 'fromage', N_HAUT, TOUTES_SAISONS, 1, "Un sauternes",
    'Une pointe de roquefort, persillée de bleu, posée sur du pain de seigle.',
    'Le persillage, harmonieusement réparti, signe un roquefort de grande qualité.',
    'Le roquefort est un peu trop fort.',
    "Le roquefort était mal conservé et devient amer et désagréable."),
  plat('Comté vieux', 'fromage', N_HAUT, TOUTES_SAISONS, 1, "Un vin jaune",
    'Une part de comté affiné dix-huit mois, aux notes de noisette.',
    'Le comté, longuement affiné, révèle des arômes de noisette grillée somptueux.',
    'Le comté est un peu trop jeune.',
    "Le comté présentait des cristaux de sel trop nombreux, rendant la pâte cassante."),
  plat('Chèvre frais', 'fromage', N_POP, CHAUD, 1, null,
    'Un petit fromage de chèvre crémeux, roulé dans des herbes fraîches.',
    'Le chèvre, d\'une fraîcheur parfaite, fond délicatement sous les herbes.',
    'Le chèvre est un peu trop acide.',
    "Le chèvre n'était plus frais et a tourné, dégageant une odeur forte."),
  plat('Munster', 'fromage', N_MOYEN, FROID, 1, "Un gewurztraminer",
    'Un munster odorant, servi avec des graines de cumin.',
    'Le munster, parfaitement affiné, embaume délicieusement la table entière.',
    'Le munster est un peu jeune.',
    "Le munster était trop fort et son odeur a envahi toute la pièce."),
  plat('Reblochon', 'fromage', N_MOYEN, FROID, 1, "Un vin de Savoie",
    'Un reblochon onctueux, croûte orangée, cœur coulant.',
    'Le reblochon, parfaitement affiné, est d\'une onctuosité remarquable.',
    'Le reblochon est un peu trop ferme.',
    "Le reblochon était mal conservé et présente un goût rance désagréable."),
  plat('Fromage blanc à la crème', 'fromage', N_POP, TOUTES_SAISONS, 1, null,
    'Un fromage blanc battu, nappé de crème fraîche épaisse.',
    'Le fromage blanc, légèrement battu, est d\'une fraîcheur et d\'une douceur parfaites.',
    'Le fromage blanc est un peu trop acide.',
    "Le fromage blanc n'était plus frais et a un goût aigre désagréable."),
  plat('Gruyère', 'fromage', N_POP, TOUTES_SAISONS, 1, null,
    'Une part de gruyère, ferme et parsemée de petits trous.',
    'Le gruyère, à point, révèle un goût de noisette fondant en bouche.',
    'Le gruyère est un peu trop sec.',
    "Le gruyère a séché trop longtemps à l'air et devient dur et cassant."),
  plat('Époisses', 'fromage', N_ARISTO, FROID, 2, "Un marc de Bourgogne",
    'Un époisses coulant, lavé au marc, à l\'odeur puissante.',
    'L\'époisses, lavé avec soin, atteint une coulance et un goût exceptionnels.',
    'L\'époisses est un peu jeune.',
    "L'époisses était trop affiné et son odeur ammoniaquée écœure les convives."),

  // ── DESSERT (15) ────────────────────────────────────────────────────
  plat('Tarte Tatin', 'dessert', N_MOYEN, FROID, 3, "Un cidre",
    'Une tarte renversée, pommes caramélisées brillant sous la pâte dorée.',
    'Les pommes, caramélisées à la perfection, brillent d\'un ambre parfait.',
    'Le caramel est un peu trop clair.',
    "Le caramel a brûlé au fond du moule et toute la tarte en prend un goût amer."),
  plat('Paris-Brest', 'dessert', N_HAUT, TOUTES_SAISONS, 4, null,
    'Une couronne de pâte à choux, garnie d\'une crème pralinée.',
    'La crème pralinée, onctueuse et croquante, comble une pâte légère et dorée.',
    'La crème est un peu trop liquide.',
    "La pâte à choux n'a pas assez gonflé et s'effondre sous le poids de la crème."),
  plat('Mille-feuille', 'dessert', N_HAUT, TOUTES_SAISONS, 4, null,
    'Des couches de pâte feuilletée croustillante, séparées de crème pâtissière.',
    'Le feuilletage, croustillant à souhait, contraste à merveille avec la crème onctueuse.',
    'Le feuilletage est un peu mou.',
    "La pâte n'a pas assez cuit et le mille-feuille s'effondre au moindre contact."),
  plat('Baba au rhum', 'dessert', N_HAUT, TOUTES_SAISONS, 3, "Un rhum vieux",
    'Un baba doré, généreusement imbibé de sirop au rhum.',
    'Le baba, gorgé de rhum, est d\'une moelleuse exceptionnelle.',
    'Le baba est un peu trop sec, pas assez imbibé.',
    "Le baba n'a pas absorbé le sirop et reste sec et dur comme du pain rassis."),
  plat('Religieuse au chocolat', 'dessert', N_HAUT, TOUTES_SAISONS, 4, null,
    'Deux choux superposés, glacés de chocolat, garnis de crème.',
    'Le glaçage, brillant et lisse, recouvre une crème pâtissière exquise.',
    'Le glaçage est un peu terne.',
    "Le glaçage a craquelé en refroidissant et la religieuse perd son éclat."),
  plat('Éclair au café', 'dessert', N_MOYEN, TOUTES_SAISONS, 3, null,
    'Un éclair allongé, glacé de fondant café, garni de crème.',
    'Le glaçage café, lisse et brillant, surmonte une crème délicatement parfumée.',
    'Le glaçage est un peu trop épais.',
    "La crème n'a pas assez refroidi et l'éclair s'affaisse en le servant."),
  plat('Savarin', 'dessert', N_HAUT, TOUTES_SAISONS, 3, "Un vin doux",
    'Une couronne moelleuse, imbibée de sirop, garnie de crème Chantilly.',
    'Le savarin, généreusement imbibé, fond délicatement sous la Chantilly.',
    'Le savarin est un peu sec au centre.',
    "Le savarin n'a pas assez imbibé et reste sec et dense au centre."),
  plat('Biscuit de Reims', 'dessert', N_HAUT, TOUTES_SAISONS, 2, "Un champagne rosé",
    'De fins biscuits roses, légers et croquants, trempés dans le champagne.',
    'Les biscuits, légers comme une plume, se marient à merveille avec les bulles.',
    'Les biscuits sont un peu trop denses.',
    "Les biscuits n'ont pas assez monté et restent denses et compacts."),
  plat('Crème brûlée', 'dessert', N_HAUT, TOUTES_SAISONS, 3, null,
    'Une crème onctueuse, surmontée d\'une fine croûte de caramel craquant.',
    'La croûte, caramélisée à la perfection, craque sous la cuillère sur une crème soyeuse.',
    'La croûte est un peu trop fine.',
    "Le sucre a brûlé sous la flamme et donne un goût âcre à toute la crème."),
  plat('Fraises Romanoff', 'dessert', N_ARISTO, CHAUD, 2, "Un champagne",
    'Des fraises macérées au curaçao, nappées de crème Chantilly.',
    'Les fraises, gorgées de curaçao, sont sublimées par une Chantilly légère.',
    'Les fraises ont un peu trop macéré.',
    "Les fraises n'étaient pas mûres et restent acides malgré la macération."),
  plat('Soufflé glacé', 'dessert', N_ARISTO, CHAUD, 4, null,
    'Un soufflé froid, monté en hauteur dans son moule à collerette.',
    'Le soufflé glacé, monté avec art, donne une illusion parfaite de soufflé chaud.',
    'Le soufflé a un peu fondu sur les bords.',
    "Le soufflé n'a pas assez pris au froid et s'effondre au démoulage."),
  plat('Gâteau Saint-Honoré', 'dessert', N_ARISTO, TOUTES_SAISONS, 5, null,
    'Une couronne de choux caramélisés entourant une crème Chiboust.',
    'Les choux, caramélisés en couronne parfaite, entourent une crème d\'une légèreté rare.',
    'Le caramel des choux est un peu collant.',
    "Le caramel a brûlé en glaçant les choux et donne un goût amer au gâteau."),
  plat('Omelette norvégienne', 'dessert', N_ARISTO, FROID, 4, null,
    'Une glace enrobée de meringue, flambée au dernier moment.',
    'La meringue, dorée à la flamme, protège parfaitement une glace encore froide.',
    'La meringue est un peu trop dorée.',
    "La glace a fondu avant le flambage et l'omelette s'effondre en une bouillie."),
  plat('Compote de pommes', 'dessert', N_POP, FROID, 1, null,
    'Une compote dorée, parfumée d\'un bâton de cannelle.',
    'La compote, mijotée avec soin, est d\'une douceur et d\'un parfum exquis.',
    'La compote est un peu trop liquide.',
    "Les pommes ont attaché au fond de la casserole et donnent un goût de brûlé."),
  plat('Sorbet au cassis', 'dessert', N_HAUT, CHAUD, 2, null,
    'Un sorbet violet intense, servi en boule dans une coupe en cristal.',
    'Le sorbet, intensément fruité, rafraîchit le palais entre les services.',
    'Le sorbet est un peu trop sucré.',
    "Le sorbet n'a pas assez pris au froid et fond en une bouillie liquide."),

  // ── PATISSERIE (12) ─────────────────────────────────────────────────
  plat('Macarons', 'patisserie', N_HAUT, TOUTES_SAISONS, 4, null,
    'De petites coques lisses et craquelées, garnies d\'une ganache.',
    'Les coques, lisses et craquelées comme il se doit, cachent une ganache fondante.',
    'Les coques sont un peu trop fragiles.',
    "Les coques n'ont pas formé de collerette et restent plates et fissurées."),
  plat('Financiers', 'patisserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'De petits gâteaux dorés, au beurre noisette et aux amandes.',
    'Le beurre noisette parfume délicieusement une mie moelleuse et dorée.',
    'Les financiers sont un peu trop denses.',
    "Le beurre a trop noirci et donne un goût amer à toute la fournée."),
  plat('Palmiers', 'patisserie', N_POP, TOUTES_SAISONS, 2, null,
    'De petits cœurs de pâte feuilletée, caramélisés et craquants.',
    'Le sucre, caramélisé uniformément, rend les palmiers délicieusement croquants.',
    'Le caramel est un peu inégal.',
    "Le sucre a brûlé d'un côté et donne un goût amer aux palmiers."),
  plat('Sablés bretons', 'patisserie', N_POP, TOUTES_SAISONS, 1, null,
    'D\'épais sablés au beurre salé, dorés et friables.',
    'Le beurre salé, généreux, donne un sablé d\'une friabilité parfaite.',
    'Les sablés sont un peu trop cuits sur les bords.',
    "La pâte a trop été travaillée et les sablés deviennent durs comme de la pierre."),
  plat('Langues de chat', 'patisserie', N_MOYEN, TOUTES_SAISONS, 2, null,
    'De fins biscuits allongés, dorés sur les bords, croustillants.',
    'Les langues de chat, fines et dorées, craquent délicatement sous la dent.',
    'Les bords sont un peu trop pâles.',
    "Les biscuits ont trop cuit et brûlent sur les bords, devenant amers."),
  plat('Tuiles aux amandes', 'patisserie', N_HAUT, TOUTES_SAISONS, 3, null,
    'De fines tuiles courbées, dorées et parsemées d\'amandes effilées.',
    'Les tuiles, courbées à la perfection sur un rouleau, sont délicieusement croustillantes.',
    'Les tuiles sont un peu trop épaisses.',
    "Les tuiles ont durci avant d'être courbées et se cassent en morceaux."),
  plat('Cannelés bordelais', 'patisserie', N_HAUT, TOUTES_SAISONS, 4, "Un rhum vieux",
    'De petits gâteaux moulés, croûte caramélisée et cœur moelleux au rhum.',
    'La croûte, sombre et caramélisée, cache un cœur moelleux parfumé au rhum.',
    'La croûte est un peu trop pâle.',
    "Les cannelés n'ont pas assez cuit et restent crus et collants au centre."),
  plat('Choux à la crème', 'patisserie', N_POP, TOUTES_SAISONS, 2, null,
    'De petits choux dorés et gonflés, garnis de crème pâtissière.',
    'Les choux, parfaitement gonflés, sont garnis d\'une crème délicatement vanillée.',
    'Les choux sont un peu trop petits.',
    "Les choux n'ont pas gonflé au four et restent plats et denses."),
  plat('Croquembouche', 'patisserie', N_ARISTO, TOUTES_SAISONS, 5, null,
    'Une pyramide de choux caramélisés, liés en une tour impressionnante.',
    'La pyramide, montée avec art, impressionne par sa hauteur et son éclat caramélisé.',
    'Le caramel est un peu collant.',
    "Le caramel a refroidi trop vite et la pyramide s'effondre en s'écroulant sur la table."),
  plat('Dacquoise', 'patisserie', N_HAUT, TOUTES_SAISONS, 4, null,
    'Des disques meringués aux amandes, superposés de crème au beurre.',
    'Les disques, croustillants et moelleux à la fois, sont un délice d\'équilibre.',
    'Les disques sont un peu trop mous.',
    "Les meringues n'ont pas assez séché et restent collantes et molles."),
  plat('Opéra', 'patisserie', N_ARISTO, TOUTES_SAISONS, 5, null,
    'Des couches de biscuit, ganache et crème au café, glacées de chocolat.',
    'Les couches, précisément égales, forment un damier parfait sous le glaçage brillant.',
    'Le glaçage est un peu terne.',
    "Les couches se sont décalées en assemblant le gâteau, ruinant l'effet visuel."),
  plat('Gâteau battu normand', 'patisserie', N_MOYEN, FROID, 3, null,
    'Un haut gâteau brioché, moulé en forme de bonnet, doré et léger.',
    'La pâte, longuement battue, donne un gâteau d\'une légèreté étonnante.',
    'Le gâteau est un peu trop dense.',
    "La pâte n'a pas assez levé dans le moule et le gâteau reste plat et lourd."),
];

function service(id, label, categorie, nb_plats) {
  return { id, label, categorie, nb_plats };
}

const structures = [
  // ── PETIT_DEJEUNER (4) ──────────────────────────────────────────────
  { type_repas: 'petit_dejeuner', niveau_financier: 'populaire', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('viennoiserie', 'Pain ou viennoiserie', 'viennoiserie', 1)],
    textes_intro: ["Le jour se lève à peine sur la cuisine encore froide.", "Une odeur de pain grillé flotte dans l'air du matin."] },
  { type_repas: 'petit_dejeuner', niveau_financier: 'bourgeois', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('viennoiserie', 'Viennoiserie', 'viennoiserie', 2)],
    textes_intro: ["La salle à manger s'emplit du parfum du café fraîchement moulu.", "Le service en porcelaine attend, posé sur la nappe blanche amidonnée."] },
  { type_repas: 'petit_dejeuner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('viennoiserie', 'Viennoiseries', 'viennoiserie', 2), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["Le domestique dispose les plats avec une précision toute militaire.", "Un rai de soleil traverse les rideaux de dentelle du petit salon."] },
  { type_repas: 'petit_dejeuner', niveau_financier: 'aristocratie', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('viennoiserie', 'Viennoiseries fines', 'viennoiserie', 2), service('fromage', 'Fromage', 'fromage', 1), service('fruits', 'Entremets léger', 'entremets', 1)],
    textes_intro: ["La salle à manger du château résonne du tintement délicat de l'argenterie.", "Un valet attend, impassible, près du buffet chargé de mets choisis."] },

  // ── GOUTER (4) ──────────────────────────────────────────────────────
  { type_repas: 'gouter', niveau_financier: 'populaire', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('viennoiserie', 'Pain ou tartine', 'viennoiserie', 1)],
    textes_intro: ["L'après-midi décline doucement, l'heure du goûter a sonné.", "Les enfants réclament déjà leur tartine en rentrant de l'école."] },
  { type_repas: 'gouter', niveau_financier: 'bourgeois', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('patisserie', 'Petite pâtisserie', 'patisserie', 1)],
    textes_intro: ["Le salon de thé bruisse de conversations légères et de tasses entrechoquées.", "Une assiette de petits gâteaux trône au centre de la table basse."] },
  { type_repas: 'gouter', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'intime',
    services: [service('boisson', 'Boisson chaude', 'boisson_chaude', 1), service('patisserie', 'Pâtisseries', 'patisserie', 2)],
    textes_intro: ["Le goûter se prend sur la terrasse, à l'ombre d'un tilleul centenaire.", "La gouvernante apporte un plateau chargé de douceurs raffinées."] },
  { type_repas: 'gouter', niveau_financier: 'aristocratie', tranche_convives: 'intime',
    services: [service('boisson', 'Thé', 'boisson_chaude', 1), service('patisserie', 'Pâtisseries fines', 'patisserie', 2), service('entremets', 'Entremets glacé', 'entremets', 1)],
    textes_intro: ["Le five o'clock tea réunit la maisonnée dans le grand salon doré.", "Le service à thé en argent massif scintille sous les lustres."] },

  // ── DEJEUNER (12) ───────────────────────────────────────────────────
  { type_repas: 'dejeuner', niveau_financier: 'populaire', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1)],
    textes_intro: ["La table de la cuisine est mise simplement, mais avec soin.", "Le déjeuner du midi réunit la famille autour de la grande table de bois."] },
  { type_repas: 'dejeuner', niveau_financier: 'populaire', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["Toute la maisonnée se presse autour de la grande table familiale.", "La marmite fume encore en arrivant sur la table commune."] },
  { type_repas: 'dejeuner', niveau_financier: 'populaire', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('plat', 'Plat principal', 'viande', 2), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Les tables ont été poussées bout à bout pour la noce du quartier.", "Le repas de fête rassemble tout le voisinage dans une joyeuse cohue."] },
  { type_repas: 'dejeuner', niveau_financier: 'bourgeois', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["La salle à manger bourgeoise s'emplit d'arômes appétissants.", "La bonne dispose les plats avec une discrétion bien rodée."] },
  { type_repas: 'dejeuner', niveau_financier: 'bourgeois', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["La famille au complet et quelques amis se retrouvent pour ce déjeuner dominical.", "La nappe damassée est sortie pour l'occasion."] },
  { type_repas: 'dejeuner', niveau_financier: 'bourgeois', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le repas de fiançailles réunit les deux familles autour d'une grande table.", "Les invités, en nombre, s'installent autour de la table dressée pour l'occasion."] },
  { type_repas: 'dejeuner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le maître d'hôtel veille à ce que chaque service soit impeccable.", "La salle à manager s'orne de fleurs fraîches coupées du matin même."] },
  { type_repas: 'dejeuner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le déjeuner d'affaires se tient dans la salle à manger d'apparat.", "Les convives discutent affaires entre deux services, verre de bordeaux à la main."] },
  { type_repas: 'dejeuner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('volaille', 'Volaille', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le grand déjeuner de réception réunit le tout-Paris dans la salle de bal aménagée.", "L'orchestre s'installe discrètement pendant que les premiers plats arrivent."] },
  { type_repas: 'dejeuner', niveau_financier: 'aristocratie', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le déjeuner se tient dans la petite salle à manger, plus intime que la grande.", "Le sommelier propose discrètement l'accord du jour."] },
  { type_repas: 'dejeuner', niveau_financier: 'aristocratie', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Les armoiries familiales ornent chaque pièce d'argenterie disposée sur la table.", "Le repas se déroule selon un protocole immuable depuis trois générations."] },
  { type_repas: 'dejeuner', niveau_financier: 'aristocratie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('gibier', 'Gibier', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 2)],
    textes_intro: ["Le grand déjeuner de chasse réunit toute la noblesse du voisinage.", "Les laquais en livrée se relaient pour servir les nombreux convives."] },

  // ── DINER (12) ──────────────────────────────────────────────────────
  { type_repas: 'diner', niveau_financier: 'populaire', tranche_convives: 'intime',
    services: [service('potage', 'Potage', 'potage', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1)],
    textes_intro: ["La soupe fume encore en arrivant sur la table du soir.", "La lampe à pétrole éclaire faiblement la table familiale."] },
  { type_repas: 'diner', niveau_financier: 'populaire', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["Toute la famille se retrouve autour de la table après une longue journée.", "Le dîner du dimanche réunit cousins et voisins venus prêter main-forte."] },
  { type_repas: 'diner', niveau_financier: 'populaire', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('plat', 'Plat principal', 'viande', 2), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le dîner de noce bat son plein dans la grange décorée pour l'occasion.", "Les tables ont été dressées dehors, sous les lampions accrochés aux arbres."] },
  { type_repas: 'diner', niveau_financier: 'bourgeois', tranche_convives: 'intime',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["La salle à manger s'éclaire des derniers feux du couchant.", "Le dîner familial se déroule au rythme tranquille des habitudes bourgeoises."] },
  { type_repas: 'diner', niveau_financier: 'bourgeois', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Quelques amis proches ont été conviés pour ce dîner du samedi soir.", "Le service à dîner en porcelaine de Limoges fait son apparition pour l'occasion."] },
  { type_repas: 'diner', niveau_financier: 'bourgeois', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le dîner de baptême réunit toute la parenté dans la grande salle louée pour l'occasion.", "Les tables, dressées en U, accueillent une assemblée nombreuse et joyeuse."] },
  { type_repas: 'diner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'intime',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Les chandeliers d'argent jettent une lumière douce sur la nappe brodée.", "Le maître d'hôtel orchestre le service avec une discrétion parfaite."] },
  { type_repas: 'diner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le dîner mondain réunit gens de lettres et industriels autour d'une même table.", "La conversation, brillante, accompagne chaque service avec esprit."] },
  { type_repas: 'diner', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('volaille', 'Volaille', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le grand dîner de gala se tient dans la salle à manger d'apparat, tout illuminée.", "L'orchestre joue en sourdine pendant que les laquais circulent entre les tables."] },
  { type_repas: 'diner', niveau_financier: 'aristocratie', tranche_convives: 'intime',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le petit salon privé accueille un dîner restreint mais raffiné.", "Le chef a composé un menu sur mesure pour cette soirée particulière."] },
  { type_repas: 'diner', niveau_financier: 'aristocratie', tranche_convives: 'tablee',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Les armoiries brodées sur les serviettes rappellent l'ancienneté de la maison.", "Le dîner se déroule selon un cérémonial réglé depuis des siècles."] },
  { type_repas: 'diner', niveau_financier: 'aristocratie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('gibier', 'Gibier', 'gibier', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 2)],
    textes_intro: ["Le grand dîner d'apparat réunit l'aristocratie locale dans la galerie illuminée.", "Les valets en grande livrée se succèdent pour servir les nombreux services."] },

  // ── SOUPER (8) ──────────────────────────────────────────────────────
  { type_repas: 'souper', niveau_financier: 'populaire', tranche_convives: 'intime',
    services: [service('plat', 'Plat léger', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["Le souper se prend tard, après une longue journée de labeur.", "Le repas du soir reste simple, à la lueur d'une chandelle."] },
  { type_repas: 'souper', niveau_financier: 'populaire', tranche_convives: 'tablee',
    services: [service('potage', 'Potage léger', 'potage', 1), service('plat', 'Plat léger', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["La famille se retrouve une dernière fois avant de gagner les chambres.", "Le souper réunit les derniers arrivants de la journée de marché."] },
  { type_repas: 'souper', niveau_financier: 'bourgeois', tranche_convives: 'intime',
    services: [service('potage', 'Potage léger', 'potage', 1), service('plat', 'Plat léger', 'volaille', 1), service('fromage', 'Fromage', 'fromage', 1)],
    textes_intro: ["Après la soirée au théâtre, un souper léger attend les convives.", "La maison, calme à cette heure tardive, accueille un souper discret."] },
  { type_repas: 'souper', niveau_financier: 'bourgeois', tranche_convives: 'tablee',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson léger', 'poisson', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Quelques amis prolongent la soirée autour d'un souper improvisé.", "Le souper, plus léger que le dîner, clôt agréablement la soirée."] },
  { type_repas: 'souper', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson léger', 'poisson', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert léger', 'entremets', 1)],
    textes_intro: ["Au retour de l'Opéra, un souper raffiné attend les invités.", "Le petit salon s'est transformé en salle de souper pour l'occasion."] },
  { type_repas: 'souper', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'tablee',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('volaille', 'Volaille froide', 'volaille', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le souper après le bal réunit les danseurs essoufflés et affamés.", "Les conversations animées se prolongent autour des derniers mets de la nuit."] },
  { type_repas: 'souper', niveau_financier: 'aristocratie', tranche_convives: 'intime',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson fin', 'poisson', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Entremets glacé', 'entremets', 1)],
    textes_intro: ["Le souper privé se tient dans le boudoir, loin de l'agitation du bal.", "Une collation raffinée a été préparée pour clore la soirée en toute intimité."] },
  { type_repas: 'souper', niveau_financier: 'aristocratie', tranche_convives: 'tablee',
    services: [service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('volaille', 'Volaille froide', 'volaille', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le souper qui suit le grand bal rassemble une assemblée encore en habits de soirée.", "Les lustres, encore allumés, éclairent une table dressée à la hâte mais avec art."] },

  // ── BANQUET (3) ─────────────────────────────────────────────────────
  { type_repas: 'banquet', niveau_financier: 'bourgeois', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('volaille', 'Volaille', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('dessert', 'Dessert', 'dessert', 1)],
    textes_intro: ["Le banquet de la corporation réunit artisans et notables du quartier.", "Les tables, dressées en longueur dans la salle des fêtes, attendent leur centaine de convives."] },
  { type_repas: 'banquet', niveau_financier: 'grande_bourgeoisie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 1), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('volaille', 'Volaille', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 2)],
    textes_intro: ["Le banquet de mariage réunit deux grandes familles dans la salle de l'hôtel particulier.", "L'orchestre joue en sourdine tandis que défilent les nombreux services du repas."] },
  { type_repas: 'banquet', niveau_financier: 'aristocratie', tranche_convives: 'banquet',
    services: [service('potage', 'Potage', 'potage', 1), service('hors_doeuvre', "Hors-d'œuvre", 'hors_d_oeuvre', 2), service('poisson', 'Poisson', 'poisson', 1), service('plat', 'Plat principal', 'viande', 1), service('gibier', 'Gibier', 'gibier', 1), service('volaille', 'Volaille', 'volaille', 1), service('legume', 'Légume', 'legume', 1), service('fromage', 'Fromage', 'fromage', 1), service('entremets', 'Entremets', 'entremets', 1), service('dessert', 'Dessert', 'dessert', 2)],
    textes_intro: ["Le grand banquet du château réunit toute l'aristocratie de la région sous les ors de la galerie.", "Cent convives prennent place tandis que résonnent les premiers accords de l'orchestre."] },
];

module.exports = { plats, structures };
