// Calendrier des saints du rit romain pour la France (fin XIXe)
// Basé sur le martyrologe romain tridentin + saints français traditionnels
// Chaque saint : { mmdd, name, domain, desc }

const saints = [
  { mmdd: '01-01', name: 'Saint Odilon — Octave de Noël', domain: 'Abbés',
    desc: 'Patron des abbayes et des monastères. Quatrième abbé de Cluny, il institua la fête des morts dans l\'ordre bénédictin.' },
  { mmdd: '01-02', name: 'Saint Basile le Grand', domain: 'Pères de l\'Église, Docteurs',
    desc: 'Évêque de Césarée en Cappadoce, Père de l\'Église grecque. Il rédigea la règle monastique qui porte son nom et lutta contre l\'arianisme. Patron des réformateurs religieux.' },
  { mmdd: '01-03', name: 'Sainte Geneviève', domain: 'Patronne de Paris',
    desc: 'Vierge consacrée, elle protégea Paris de l\'invasion d\'Attila par ses prières au Ve siècle. Patronne de la ville de Paris et de la gendarmerie française. Sa châsse repose à Saint-Étienne-du-Mont.' },
  { mmdd: '01-04', name: 'Saint Tite', domain: 'Évêques, Disciples de saint Paul',
    desc: 'Disciple et collaborateur de saint Paul, évêque de Crète. À qui Paul adressa l\'une de ses épîtres pastorales.' },
  { mmdd: '01-05', name: 'Saint Télémaque', domain: 'Martyrs, Moines',
    desc: 'Moine oriental qui se jeta dans l\'arène du Colisée pour séparer les gladiateurs, provoquant l\'abolition des jeux par l\'empereur Honorius en 404.' },
  { mmdd: '01-06', name: 'Épiphanie — Les Rois Mages', domain: 'Fête du Seigneur',
    desc: 'Manifestation de Jésus aux nations par la visite des Rois Mages Gaspard, Melchior et Balthazar. La plus ancienne fête chrétienne après Pâques.' },
  { mmdd: '01-07', name: 'Saint Raymond de Peñafort', domain: 'Confesseurs, Juristes',
    desc: 'Dominicain espagnol, grand canoniste du XIIIe siècle. Maître général de l\'ordre des Prêcheurs, il codifia le droit canon. Patron des avocats.' },
  { mmdd: '01-08', name: 'Saint Lucien de Beauvais', domain: 'Martyrs, Évangélisateurs',
    desc: 'Prêtre romain envoyé évangéliser la Gaule avec saint Denis au IIIe siècle. Martyr à Beauvais. Patron de la Picardie.' },
  { mmdd: '01-09', name: 'Saints Julien et Basilisse', domain: 'Martyrs',
    desc: 'Époux chrétiens d\'Antioche qui vécurent dans la chasteté et le service des pauvres. Martyrisés sous Dioclétien. Patrons des couples.' },
  { mmdd: '01-10', name: 'Saint Guillaume de Bourges', domain: 'Évêques',
    desc: 'Archevêque de Bourges au XIIIe siècle, ancien moine cistercien de Pontigny. Connu pour sa sainteté et sa charité envers les pauvres.' },
  { mmdd: '01-11', name: 'Saint Théodose le Cénobiarque', domain: 'Moines, Fondateurs',
    desc: 'Père du cénobitisme en Orient, il organisa les premières communautés monastiques autour de Bethléem au Ve siècle.' },
  { mmdd: '01-12', name: 'Saint Benoît Biscop', domain: 'Moines, Fondateurs',
    desc: 'Abbé de Wearmouth en Angleterre, fondateur de monastères. Cinq fois pèlerin à Rome, il rapporta livres et reliques pour instruire les moines anglo-saxons.' },
  { mmdd: '01-13', name: 'Saint Hilaire de Poitiers', domain: 'Évêques, Docteurs de l\'Église',
    desc: 'Évêque de Poitiers au IVe siècle, grand défenseur de la divinité du Christ contre l\'arianisme. Surnommé l\'Athanase de l\'Occident.' },
  { mmdd: '01-14', name: 'Saint Félix de Nole', domain: 'Prêtres, Confesseurs',
    desc: 'Prêtre de Nole en Campanie, emprisonné pour sa foi sous Dioclétien. Sa vie simple et charitable en fit un saint très populaire dans l\'Italie chrétienne primitive.' },
  { mmdd: '01-15', name: 'Saint Paul l\'Ermite', domain: 'Ermites',
    desc: 'Premier ermite chrétien de Thébaïde en Égypte, fui les persécutions pour vivre cent treize ans dans le désert. Visitée par saint Antoine.' },
  { mmdd: '01-16', name: 'Saint Marcel Ier', domain: 'Papes',
    desc: 'Pape au début du IVe siècle, exilé par Maxence pour sa fermeté dans la foi. Organisa les communautés chrétiennes après la persécution. Patron des papetiers.' },
  { mmdd: '01-17', name: 'Saint Antoine le Grand', domain: 'Pères du désert, Moines',
    desc: 'Père du monachisme chrétien. Après avoir distribué ses biens, il vécut soixante ans dans le désert égyptien. Patron des pauvres et des animaux.' },
  { mmdd: '01-18', name: 'Chaire de saint Pierre à Rome', domain: 'Fête apostolique',
    desc: 'Commemoration du siège apostolique de Rome établi par saint Pierre après son arrivée dans la Ville Éternelle. Fondement de l\'Église de Rome.' },
  { mmdd: '01-19', name: 'Saint Wulstan', domain: 'Évêques',
    desc: 'Évêque de Worcester en Angleterre au XIe siècle, dernier évêque anglo-saxon après la conquête normande. Réformateur du clergé.' },
  { mmdd: '01-20', name: 'Saints Fabien et Sébastien', domain: 'Papes, Martyrs',
    desc: 'Fabien, pape martyr au IIIe siècle, et Sébastien, officier romain martyrisé par les flèches. Sébastien est patron des archers et des soldats.' },
  { mmdd: '01-21', name: 'Sainte Agnès', domain: 'Vierges, Martyres',
    desc: 'Jeune vierge romaine martyrisée à treize ans sous Dioclétien. L\'une des vierges les plus célèbres de l\'Église primitive. Patronne des fiancés.' },
  { mmdd: '01-22', name: 'Saint Vincent', domain: 'Diacres, Martyrs',
    desc: 'Diacre de Saragosse, l\'un des premiers martyrs espagnols. Brûlé sur un gril à Valence en 304. Patron des vignerons et des charpentiers.' },
  { mmdd: '01-23', name: 'Sainte Émérentienne', domain: 'Vierges, Martyres',
    desc: 'Sœur de lait de saint Laurent. Martyre lapidée à Rome au IIIe siècle alors qu\'elle priait sur le tombeau de saint Laurent.' },
  { mmdd: '01-24', name: 'Saint François de Sales', domain: 'Évêques, Docteurs',
    desc: 'Évêque de Genève au XVIIe siècle, fondateur de l\'ordre de la Visitation. Patron des journalistes et des écrivains, connu pour sa douceur.' },
  { mmdd: '01-25', name: 'Conversion de saint Paul', domain: 'Fête apostolique',
    desc: 'Commémoration de la conversion de Saul de Tarse sur le chemin de Damas. Le persécuteur devint le plus grand missionnaire de l\'Église primitive.' },
  { mmdd: '01-26', name: 'Sainte Paule', domain: 'Veuves, Moniales',
    desc: 'Dame romaine de l\'aristocratie, devenue veuve, elle distribua leurs biens et suivit saint Jérusalem à Bethléem. Fondatrice de monastères.' },
  { mmdd: '01-27', name: 'Saint Jean Chrysostome', domain: 'Évêques, Docteurs',
    desc: 'Archevêque de Constantinople au IVe siècle. Surnommé Bouche d\'or pour son éloquence. Grand prédicateur, réformateur du clergé, exilé pour son courage.' },
  { mmdd: '01-28', name: 'Saint Charlemagne', domain: 'Empereurs, Confesseurs',
    desc: 'Empereur d\'Occident au VIIIe-IXe siècle, protecteur de l\'Église et réformateur des écoles. Son culte est particulièrement célébré en France et à Aix-la-Chapelle.' },
  { mmdd: '01-29', name: 'Saint Gildas', domain: 'Moines, Abbés',
    desc: 'Moine breton du VIe siècle, surnommé le Sage. Auteur d\'un traité sur la ruine de la Bretagne. L\'un des grands saints évangélisateurs de l\'Armorique.' },
  { mmdd: '01-30', name: 'Sainte Martine', domain: 'Vierges, Martyres',
    desc: 'Jeune romaine martyrisée au IIIe siècle sous Alexandre Sévère. Ses reliques furent retrouvées au XVIIe siècle à Rome. L\'une des saintes patronnes de Rome.' },
  { mmdd: '01-31', name: 'Saint Pierre Nolasque', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'Ordre de la Merci pour le rachat des captifs aux XIIe-XIIIe siècle. Consacré à délivrer les chrétiens prisonniers des Maures.' },

  { mmdd: '02-01', name: 'Saint Ignace d\'Antioche', domain: 'Évêques, Martyrs',
    desc: 'Évêque d\'Antioche au IIe siècle, disciple de saint Jean. Porté enchaîné à Rome pour y être livré aux bêtes. Auteur de sept lettres fameuses.' },
  { mmdd: '02-02', name: 'Chandeleur — Purification de la Vierge', domain: 'Fête de la Vierge',
    desc: 'Présentation de Jésus au Temple et purification de Marie. Fête de la lumière quarante jours après Noël. Bénédiction des cierges et procession.' },
  { mmdd: '02-03', name: 'Saint Blaise de Sébaste', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Sébaste en Arménie, médecin et martyr du IVe siècle. Patron des maladies de la gorge et des médecins. Bénédiction des gorges le jour de sa fête.' },
  { mmdd: '02-04', name: 'Saint André Corsini', domain: 'Évêques',
    desc: 'Évêque carmélite de Fiesole en Italie au XIVe siècle. Connu pour ses miracles et sa charité envers les pauvres. Patron de la ville de Fiesole.' },
  { mmdd: '02-05', name: 'Sainte Agathe', domain: 'Vierges, Martyres',
    desc: 'Jeune vierge sicilienne martyrisée à Catane au IIIe siècle, seins coupés pour sa foi. Patronne des nourrices, des bijoutiers et de la ville de Catane.' },
  { mmdd: '02-06', name: 'Saint Tite — Saint Dorothée', domain: 'Martyrs',
    desc: 'Officier romain et saint Théophile, martyrisés à Antioche. Tite présenta une requête à l\'empereur pour les chrétiens persécutés et fut exécuté.' },
  { mmdd: '02-07', name: 'Saint Romuald', domain: 'Abbés, Fondateurs',
    desc: 'Fondateur de l\'ordre des Camaldules au Xe-XIe siècle. Moine ermite italien, réformateur de la vie monastique.' },
  { mmdd: '02-08', name: 'Saint Jean de Matha', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'Ordre de la Trinité (Trinitaires) au XIIe siècle. Consacré au rachat des chrétiens captifs des infidèles.' },
  { mmdd: '02-09', name: 'Sainte Apolline', domain: 'Vierges, Martyres',
    desc: 'Diaconesse d\'Alexandrie au IIIe siècle, martyrisée par la foule païenne. Tous les dents arrachées, elle se jeta dans les flammes. Patronne des dentistes.' },
  { mmdd: '02-10', name: 'Sainte Scholastique', domain: 'Vierges, Moniales',
    desc: 'Sœur jumelle de saint Benoît, fondatrice du monachisme féminin bénédictin au VIe siècle. Patronne des moniales et des éducatrices.' },
  { mmdd: '02-11', name: 'Apparition de la Vierge à Lourdes', domain: 'Apparitions mariales',
    desc: 'Première apparition de la Vierge Marie à Bernadette Soubirous dans la grotte de Massabielle à Lourdes en 1858. Depuis, Lourdes est le plus grand pèlerinage de France.' },
  { mmdd: '02-12', name: 'Saints Médard et Godard', domain: 'Évêques',
    desc: 'Saint Médard, évêque de Noyon au VIe siècle, protecteur des paysans. Saint Godard, évêque de Rouen. Tous deux grands évangélisateurs de la Gaule du Nord.' },
  { mmdd: '02-13', name: 'Saint Benoît d\'Aniane', domain: 'Abbés, Réformateurs',
    desc: 'Moine languedocien du VIIIe siècle, grand réformateur du monachisme bénédictin en Gaule. Conseiller de Louis le Pieux pour les affaires religieuses.' },
  { mmdd: '02-14', name: 'Saint Valentin', domain: 'Prêtres, Martyrs',
    desc: 'Prêtre romain martyrisé au IIIe siècle. Patron des amoureux et des fiancés. La tradition d\'échanger des messages d\'amour ce jour-là est déjà florissante à la Belle Époque.' },
  { mmdd: '02-15', name: 'Saints Faustin et Jovite', domain: 'Martyrs',
    desc: 'Frères martyrs de Brescia en Lombardie au IIe siècle. Leur culte est ancien et célébré dans toute l\'Italie du Nord.' },
  { mmdd: '02-16', name: 'Sainte Julienne de Nicomédie', domain: 'Vierges, Martyres',
    desc: 'Vierge martyre de Nicomédie au IVe siècle, persécutée sous Dioclétien. Décapitée après avoir refusé d\'épouser un gouverneur païen.' },
  { mmdd: '02-17', name: 'Saint Flavien', domain: 'Martyrs, Patriarches',
    desc: 'Patriarche de Constantinople au Ve siècle, défenseur de la foi contre le monophysisme. Battit à mort lors du Brigandage d\'Éphèse en 449.' },
  { mmdd: '02-18', name: 'Saint Siméon de Jérusalem', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Jérusalem au IIe siècle, fils de Clopas et parent du Seigneur. Crucifié sous Trajan à l\'âge de cent vingt ans.' },
  { mmdd: '02-19', name: 'Saint Barbatus de Bénévent', domain: 'Évêques',
    desc: 'Évêque de Bénévent au VIIe siècle. Convertit les Lombards au christianisme et fit abattre l\'arbre sacré païen auquel ils rendaient un culte.' },
  { mmdd: '02-20', name: 'Saint Eucher d\'Orléans', domain: 'Évêques',
    desc: 'Évêque d\'Orléans au VIIIe siècle, exilé par Charles Martel pour avoir défendu les biens de l\'Église contre les confiscations. Mort en exil à Cologne.' },
  { mmdd: '02-21', name: 'Saint Germain de Paris', domain: 'Évêques',
    desc: 'Évêque de Paris au VIe siècle, conseiller du roi Childebert. Il convertit la Gaule franque et fit construire les premières églises parisiennes.' },
  { mmdd: '02-22', name: 'Chaire de saint Pierre à Antioche', domain: 'Fête apostolique',
    desc: 'Commémoration du siège apostolique d\'Antioche, premier évêché de saint Pierre avant son départ pour Rome. Marque l\'unité de l\'Église.' },
  { mmdd: '02-23', name: 'Saint Pierre Damien', domain: 'Évêques, Docteurs',
    desc: 'Moine, évêque et cardinal du XIe siècle. Grand réformateur du clergé et défenseur de la discipline ecclésiastique. Docteur de l\'Église.' },
  { mmdd: '02-24', name: 'Saint Matthias', domain: 'Apôtres',
    desc: 'Apôtre choisi par le sort pour remplacer Judas Iscariote après l\'Ascension. Évangélisa la Judée et la Cappadoce. Martyrisé en Éthiopie.' },
  { mmdd: '02-25', name: 'Saint Césaire de Nazianze', domain: 'Confesseurs',
    desc: 'Médecin et haut fonctionnaire byzantin au IVe siècle, frère de saint Grégoire de Nazianze. Convertit l\'Orient par son exemple de vie chrétienne.' },
  { mmdd: '02-26', name: 'Saint Nestor de Magydos', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Magydos en Pamphylie au IIIe siècle. Condamné aux flammes mais sauvé selon la tradition, il subit finalement le martyre sous Dèce.' },
  { mmdd: '02-27', name: 'Saint Gabriel de l\'Addolorata', domain: 'Confesseurs',
    desc: 'Passionniste italien du XIXe siècle, mort à vingt-quatre ans. Patron des séminaristes et des jeunes. Canonisé en 1920, son culte se répand rapidement dans les années 1890.' },
  { mmdd: '02-28', name: 'Saint Hilaire le Jeune', domain: 'Papes',
    desc: 'Pape du Ve siècle. Défendit l\'autorité du siège romain contre les ingérences impériales. Lutta contre l\'eutychianisme.' },

  { mmdd: '03-01', name: 'Saint Aubin d\'Angers', domain: 'Évêques',
    desc: 'Évêque d\'Angers au VIe siècle, défenseur des faibles et des opprimés. Fit admettre le principe de l\'inviolabilité des esclaves réfugiés à l\'église.' },
  { mmdd: '03-02', name: 'Saints Cédoine et ses compagnons', domain: 'Martyrs',
    desc: 'Groupe de martyrs persans du IVe siècle, exécutés sous le roi Sapor II pour avoir refusé d\'adorer le feu et les divinités zoroastriennes.' },
  { mmdd: '03-03', name: 'Sainte Cunégonde', domain: 'Impératrices, Moniales',
    desc: 'Impératrice du Saint-Empire au XIe siècle, épouse de saint Henri II. Après la mort de son époux, elle entra au monastère de Kaufungen.' },
  { mmdd: '03-04', name: 'Saint Casimir', domain: 'Princes, Confesseurs',
    desc: 'Prince de Pologne au XVe siècle, réputé pour sa piété, sa chasteté et son dévouement aux pauvres. Patron de la Pologne et de la Lituanie.' },
  { mmdd: '03-05', name: 'Saint Théophile', domain: 'Confesseurs',
    desc: 'Moine et évêque, connu pour son humilité et sa patience face aux persécutions intérieures dans l\'Église d\'Orient au IVe siècle.' },
  { mmdd: '03-06', name: 'Sainte Colette', domain: 'Vierges, Moniales',
    desc: 'Religieuse clarisse de Corbie au XVe siècle, réformatrice de l\'ordre de Sainte-Claire. Patronne des femmes enceintes et des dentellières.' },
  { mmdd: '03-07', name: 'Saint Thomas d\'Aquin', domain: 'Docteurs de l\'Église',
    desc: 'Théologien dominicain du XIIIe siècle, auteur de la Somme Théologique. Le plus grand philosophe et théologien de l\'Église catholique. Patron des universités.' },
  { mmdd: '03-08', name: 'Saint Jean de Dieu', domain: 'Confesseurs, Fondateurs',
    desc: 'Militaire portugais devenu infirmier, fondateur de l\'ordre des Frères de la Charité au XVIe siècle. Patron des hôpitaux et des malades.' },
  { mmdd: '03-09', name: 'Sainte Françoise Romaine', domain: 'Veuves, Fondatrices',
    desc: 'Mère de famille romaine du XVe siècle, fondatrice des Oblates de Tor de\' Specchi. Protégea Rome des fléaux par ses prières. Patronne des automobilistes.' },
  { mmdd: '03-10', name: 'Saint Macaire de Jérusalem', domain: 'Évêques',
    desc: 'Évêque de Jérusalem au IVe siècle. Assista au concile de Nicée et présida à la construction de l\'église du Saint-Sépulcre sur le Golgotha.' },
  { mmdd: '03-11', name: 'Saint Euloge de Cordoue', domain: 'Martyrs',
    desc: 'Prêtre martyr de Cordoue au IXe siècle sous la domination musulmane. Défenseur des chrétiens mozarabes. Décapité pour avoir caché une chrétienne.' },
  { mmdd: '03-12', name: 'Saint Grégoire le Grand', domain: 'Papes, Docteurs',
    desc: 'Pape du VIe siècle. Envoya Augustin évangéliser l\'Angleterre, réforma le chant liturgique (chant grégorien). Père de la chrétienté médiévale.' },
  { mmdd: '03-13', name: 'Saint Léon de Rome', domain: 'Évêques, Ermites',
    desc: 'Saint ermite et évêque du sud de l\'Italie au Xe siècle. Connu pour ses miracles et sa vie ascétique dans la région de Lucques.' },
  { mmdd: '03-14', name: 'Sainte Mathilde', domain: 'Reines',
    desc: 'Reine de Germanie au Xe siècle, épouse d\'Henri Ier l\'Oiseleur. Fondatrice d\'églises et de monastères, modèle de piété et de charité.' },
  { mmdd: '03-15', name: 'Saint Zacharie', domain: 'Papes',
    desc: 'Pape au VIIIe siècle, dernier pape d\'origine grecque. Protégea Rome des Lombards et correspondit avec saint Boniface évangélisant la Germanie.' },
  { mmdd: '03-16', name: 'Saint Héribert de Cologne', domain: 'Évêques',
    desc: 'Archevêque de Cologne au XIe siècle, chancelier de l\'empire sous Otton III. Fondateur de l\'abbaye de Deutz.' },
  { mmdd: '03-17', name: 'Saint Patrick', domain: 'Évêques, Patron d\'Irlande',
    desc: 'Évêque et apôtre de l\'Irlande au Ve siècle. Il évangélisa l\'île d\'Émeraude, chassa les serpents et utilisa le trèfle pour expliquer la Trinité.' },
  { mmdd: '03-18', name: 'Saint Cyrille de Jérusalem', domain: 'Évêques, Docteurs',
    desc: 'Archevêque de Jérusalem au IVe siècle. Ses catéchèses sont un témoignage précieux de la foi chrétienne primitive et de la liturgie de Jérusalem.' },
  { mmdd: '03-19', name: 'Saint Joseph', domain: 'Époux de la Vierge, Patron universel',
    desc: 'Époux de la Vierge Marie et père nourricier de Jésus. Charpentier de Nazareth. Patron des artisans, des travailleurs et de l\'Église universelle. Patron de la Belgique.' },
  { mmdd: '03-20', name: 'Saint Wulfran de Sens', domain: 'Évêques, Missionnaires',
    desc: 'Archevêque de Sens au VIIIe siècle, missionnaire en Frise où il prêcha l\'Évangile avec saint Willibrord après avoir démissionné de son siège.' },
  { mmdd: '03-21', name: 'Saint Benoît de Nursie', domain: 'Pères du monachisme, Abbés',
    desc: 'Fondateur du monachisme occidental au VIe siècle et auteur de la Règle bénédictine. Patron de l\'Europe et des moines d\'Occident.' },
  { mmdd: '03-22', name: 'Saint Basile d\'Ancyre', domain: 'Prêtres, Martyrs',
    desc: 'Prêtre d\'Ancyre (Ankara) au IVe siècle, mort martyrisé sous Julien l\'Apostat pour avoir refusé d\'apostasier et de sacrifier aux idoles.' },
  { mmdd: '03-23', name: 'Saint Benoît Le Borgne', domain: 'Moines, Martyrs',
    desc: 'Moine polonais du XIe siècle, ermite près de Kiev. Martyrisé par des brigands païens avec ses compagnons. L\'un des premiers saints slaves.' },
  { mmdd: '03-24', name: 'Sainte Catherine de Suède', domain: 'Vierges',
    desc: 'Fille de sainte Brigitte de Suède, elle lui succéda comme supérieure de l\'ordre du Saint-Sauveur au XIVe siècle. Modèle de piété filiale.' },
  { mmdd: '03-25', name: 'Annonciation de la Vierge Marie', domain: 'Fête de la Vierge',
    desc: 'L\'ange Gabriel annonce à Marie qu\'elle concevra le Fils de Dieu par l\'opération du Saint-Esprit. Neuf mois avant Noël. Mystère de l\'Incarnation.' },
  { mmdd: '03-26', name: 'Saint Ludger de Münster', domain: 'Évêques',
    desc: 'Évêque et missionnaire de Frise au VIIIe siècle, disciple d\'Alcuin. Évangélisa les Saxons et fonda l\'évêché de Münster.' },
  { mmdd: '03-27', name: 'Saint Rupert de Salzbourg', domain: 'Évêques, Fondateurs',
    desc: 'Évêque et apôtre de Bavière au VIIe siècle. Fondateur de l\'abbaye de Saint-Pierre à Salzbourg. Patron de la ville de Salzbourg.' },
  { mmdd: '03-28', name: 'Saint Gontran', domain: 'Rois, Confesseurs',
    desc: 'Roi de Bourgogne et d\'Orléans au VIe siècle, petit-fils de Clovis. Connu pour sa justice, sa piété et sa protection des pauvres et des églises.' },
  { mmdd: '03-29', name: 'Saint Eustache de Luxeuil', domain: 'Abbés',
    desc: 'Abbé de Luxeuil au VIIe siècle, successeur de saint Colomban. Étendit la règle colombanienne en Gaule et convertit les tribus germaniques.' },
  { mmdd: '03-30', name: 'Saint Jean Climaque', domain: 'Moines, Docteurs',
    desc: 'Moine et abbé du Sinaï au VIIe siècle, auteur de L\'Échelle Sainte, guide spirituel classique de l\'Orient chrétien.' },
  { mmdd: '03-31', name: 'Saint Gui de Pomposa', domain: 'Abbés',
    desc: 'Abbé de Pomposa en Italie au XIe siècle. Il réforma son abbaye et en fit un centre intellectuel rayonnant, accueillant de nombreux étudiants.' },

  { mmdd: '04-01', name: 'Saint Hugues de Grenoble', domain: 'Évêques',
    desc: 'Évêque de Grenoble au XIIe siècle, confesseur. Il introduisit saint Bruno et ses compagnons dans les Alpes, fondant la Grande Chartreuse. Cinquante-deux ans d\'épiscopat.' },
  { mmdd: '04-02', name: 'Saint François de Paule', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'ordre des Minimes au XVe siècle. Ermite calabrais, il vécut en pénitence et dans l\'humilité. Patron de la Calabre.' },
  { mmdd: '04-03', name: 'Saint Richard de Chichester', domain: 'Évêques',
    desc: 'Évêque de Chichester au XIIIe siècle. Connu pour sa charité envers les veuves et les orphelins, et pour son zèle à évangéliser les campagnes anglaises.' },
  { mmdd: '04-04', name: 'Saint Isidore de Séville', domain: 'Évêques, Docteurs',
    desc: 'Archevêque de Séville au VIIe siècle, savant encyclopédiste. Ses Étymologies sont la somme du savoir antique transmis au Moyen Âge. Patron d\'Internet.' },
  { mmdd: '04-05', name: 'Saint Vincent Ferrier', domain: 'Confesseurs, Prédicateurs',
    desc: 'Dominicain valencien du XVe siècle. Grand prédicateur itinérant parcourant l\'Europe pour convertir les hérétiques et les juifs. Patron des maçons.' },
  { mmdd: '04-06', name: 'Saint Sixte Ier', domain: 'Papes, Martyrs',
    desc: 'Pape du IIe siècle, successeur de saint Alexandre Ier. Martyr sous l\'empereur Hadrien, il gouverna l\'Église pendant environ dix ans.' },
  { mmdd: '04-07', name: 'Saint Jean-Baptiste de La Salle', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre français du XVIIe siècle, fondateur des Frères des Écoles Chrétiennes. Révolutionna l\'enseignement populaire. Patron des enseignants.' },
  { mmdd: '04-08', name: 'Saint Aedh de Kildare', domain: 'Évêques',
    desc: 'Évêque et confesseur irlandais du VIe siècle. Disciple de saint David, il fonda plusieurs églises en Irlande et mena une vie d\'ascèse.' },
  { mmdd: '04-09', name: 'Sainte Valdetrude', domain: 'Moniales',
    desc: 'Veuve et moniale belge du VIIe siècle, épouse de saint Vincent Madelgaire. Après la mort de son époux, elle fonda le monastère de Mons. Patronne du Hainaut.' },
  { mmdd: '04-10', name: 'Saint Fulbert de Chartres', domain: 'Évêques',
    desc: 'Évêque de Chartres au XIe siècle, grand bâtisseur. Fit reconstruire la cathédrale de Chartres et fonda une école célèbre de théologie.' },
  { mmdd: '04-11', name: 'Saint Léon le Grand', domain: 'Papes, Docteurs',
    desc: 'Pape du Ve siècle. Il arrêta Attila aux portes de Rome et définit la doctrine de l\'Incarnation au concile de Chalcédoine. Grand docteur de l\'Église.' },
  { mmdd: '04-12', name: 'Saint Sabas le Goth', domain: 'Martyrs',
    desc: 'Martyr goth du IVe siècle. Refusa de manger des viandes sacrifiées aux idoles et fut noyé dans un fleuve par les Goths païens.' },
  { mmdd: '04-13', name: 'Saint Martin Ier', domain: 'Papes, Martyrs',
    desc: 'Pape et martyr du VIIe siècle, exilé par l\'empereur Constant II pour avoir condamné le monothélisme. Mort en Crimée dans la souffrance pour la foi.' },
  { mmdd: '04-14', name: 'Saint Lambert de Lyon', domain: 'Évêques, Confesseurs',
    desc: 'Évêque de Lyon au VIIe siècle, connu pour sa science et sa piété. Ancien abbé de Fontenelle, il gouverna l\'Église de Lyon avec sagesse.' },
  { mmdd: '04-15', name: 'Sainte Paterne d\'Avranches', domain: 'Évêques',
    desc: 'Évêque d\'Avranches en Normandie au VIe siècle. Disciple de saint Germain l\'Écossais, il évangélisa la région et fonda le monastère de Scissy.' },
  { mmdd: '04-16', name: 'Saint Fructueux de Braga', domain: 'Évêques, Martyrs',
    desc: 'Archevêque de Braga et de Compostelle au VIIe siècle. Patron de la Galice. Auteur d\'une règle monastique et défenseur de la foi chrétienne en Espagne wisigothique.' },
  { mmdd: '04-17', name: 'Saint Anicet', domain: 'Papes, Martyrs',
    desc: 'Pape du IIe siècle, martyr sous Marc-Aurèle. Il reçut saint Polycarpe à Rome et lutta contre l\'hérésie gnostique.' },
  { mmdd: '04-18', name: 'Sainte Gammard', domain: 'Vierges, Martyres',
    desc: 'Vierge martyre d\'Auxerre au IIIe siècle, morte pour avoir refusé d\'adorer les faux dieux. Son culte est célébré en Bourgogne.' },
  { mmdd: '04-19', name: 'Saint Georges de Jérusalem', domain: 'Abbés, Moines',
    desc: 'Abbé du monastère de Choziba en Palestine au VIe siècle. Connu pour sa vie de prière et de jeûne dans le désert de Judée.' },
  { mmdd: '04-20', name: 'Sainte Agnès de Montepulciano', domain: 'Vierges, Moniales',
    desc: 'Moniale dominicaine du XIIIe siècle. Prieure du couvent de Montepulciano en Toscane, elle eut de nombreuses visions mystiques.' },
  { mmdd: '04-21', name: 'Saint Anselme de Cantorbéry', domain: 'Évêques, Docteurs',
    desc: 'Archevêque de Cantorbéry au XIIe siècle, philosophe et théologien. Père de la scolastique, créateur du célèbre argument ontologique de l\'existence de Dieu.' },
  { mmdd: '04-22', name: 'Saint Soter et saint Caïus', domain: 'Papes, Martyrs',
    desc: 'Deux papes du IIe siècle et IIIe siècle, martyrs. Sother régna sous Marc-Aurèle, Caïus sous Dioclétien. Tous deux pasteurs des premiers chrétiens de Rome.' },
  { mmdd: '04-23', name: 'Saint Georges', domain: 'Martyrs, Chevaliers',
    desc: 'Soldat romain et martyr du IVe siècle, célèbre pour avoir terrassé le dragon. Patron de l\'Angleterre, de la Catalogne et de la chevalerie.' },
  { mmdd: '04-24', name: 'Saint Fidèle de Sigmaringen', domain: 'Martyrs, Prédicateurs',
    desc: 'Capucin allemand du XVIIe siècle, prédicateur dans les Grisons suisses pendant la Contre-Réforme. Martyr tué par des paysans protestants.' },
  { mmdd: '04-25', name: 'Saint Marc l\'Évangéliste', domain: 'Évangélistes',
    desc: 'Évangéliste, disciple de saint Pierre et fondateur de l\'Église d\'Alexandrie. Auteur du second évangile. Patron des notaires et de Venise.' },
  { mmdd: '04-26', name: 'Saints Clétus et Marcellin', domain: 'Papes, Martyrs',
    desc: 'Clétus, troisième pape après Pierre, et Marcellin, pape au IIIe siècle. Tous deux morts martyrs pour leur foi à Rome.' },
  { mmdd: '04-27', name: 'Saint Zita', domain: 'Vierges, Servantes',
    desc: 'Servante de la région de Lucques en Italie au XIIIe siècle. Connue pour sa piété, son humilité et ses miracles. Patronne des domestiques et des serviteurs.' },
  { mmdd: '04-28', name: 'Saint Louis-Marie Grignion de Montfort', domain: 'Confesseurs, Prédicateurs',
    desc: 'Prêtre vendéen du XVIIIe siècle. Missionnaire populaire, fondateur des Missionnaires de la Compagnie de Marie et auteur du Traité de la vraie dévotion à Marie.' },
  { mmdd: '04-29', name: 'Saint Pierre de Vérone', domain: 'Martyrs, Prédicateurs',
    desc: 'Dominicain italien du XIIIe siècle, grand prédicateur contre l\'hérésie cathare. Assassiné par des hérétiques. Patron des inquisiteurs.' },
  { mmdd: '04-30', name: 'Sainte Catherine de Sienne', domain: 'Vierges, Docteurs',
    desc: 'Tierce dominicaine et mystique du XIVe siècle. Elle convainquit le pape de revenir d\'Avignon à Rome. Docteur de l\'Église. Patronne de l\'Italie et de l\'Europe.' },

  { mmdd: '05-01', name: 'Saints Philippe et Jacques le Mineur', domain: 'Apôtres',
    desc: 'Deux apôtres du Christ. Philippe évangélisa la Phrygie, Jacques écrivit l\'épître qui porte son nom et fut le premier évêque de Jérusalem. Tous deux martyrs.' },
  { mmdd: '05-02', name: 'Saint Athanase d\'Alexandrie', domain: 'Évêques, Docteurs',
    desc: 'Patriarche d\'Alexandrie au IVe siècle, grand défenseur de la divinité du Christ contre l\'arianisme. Exilé cinq fois pour la foi. Docteur de l\'Église.' },
  { mmdd: '05-03', name: 'Invention de la Sainte Croix', domain: 'Fête du Seigneur',
    desc: 'Commémoration de la découverte de la vraie Croix du Christ par sainte Hélène, mère de Constantin, à Jérusalem en 326. L\'une des plus anciennes fêtes.' },
  { mmdd: '05-04', name: 'Sainte Monique', domain: 'Veuves, Mères de famille',
    desc: 'Mère de saint Augustin au IVe siècle. Patronne des mères chrétiennes. Par ses larmes et ses prières infatigables, elle obtint la conversion de son fils.' },
  { mmdd: '05-05', name: 'Saint Pie V', domain: 'Papes',
    desc: 'Pape dominicain du XVIe siècle. Appliqua les réformes du concile de Trente, publia le bréviaire et le missel romains. Organisa la victoire de Lépante.' },
  { mmdd: '05-06', name: 'Saint Jean avant la Porte Latine', domain: 'Fête apostolique',
    desc: 'Commémoration du martyre de saint Jean l\'Évangéliste à Rome, plongé dans une cuve d\'huile bouillante devant la Porte Latine. Il en sortit miraculeusement indemne.' },
  { mmdd: '05-07', name: 'Saint Stanislas de Szczepanów', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Cracovie au XIe siècle, martyr assassiné par le roi Boleslas II pendant la messe. Patron de la Pologne et de la ville de Cracovie.' },
  { mmdd: '05-08', name: 'Apparition de saint Michel au Mont Gargan', domain: 'Apparitions angéliques',
    desc: 'Première apparition de l\'archange Michel en Occident au Mont Gargan en Italie au Ve siècle. Fondation du sanctuaire dédié au prince des anges.' },
  { mmdd: '05-09', name: 'Saint Grégoire de Nazianze', domain: 'Évêques, Docteurs',
    desc: 'Archevêque de Constantinople au IVe siècle. Grand orateur sacré, surnommé le Théologien pour ses traités sur la Trinité. Père de l\'Église grecque.' },
  { mmdd: '05-10', name: 'Saint Antonin de Florence', domain: 'Évêques',
    desc: 'Archevêque dominicain de Florence au XVe siècle. Connu pour sa charité et sa sagesse. Auteur d\'une somme de théologie morale très influente.' },
  { mmdd: '05-11', name: 'Saint Mamert de Vienne', domain: 'Évêques',
    desc: 'Évêque de Vienne au Ve siècle. Il institua les Rogations, processions de trois jours avant l\'Ascension, pour implorer la protection divine contre les calamités.' },
  { mmdd: '05-12', name: 'Saints Nérée et Achillée', domain: 'Martyrs',
    desc: 'Soldats eunuques de la cour de Domitille, convertis et martyrisés au Ier siècle pour leur foi. Leurs corps reposent dans la catacombe de Domitille à Rome.' },
  { mmdd: '05-13', name: 'Saint Robert Bellarmin', domain: 'Évêques, Docteurs',
    desc: 'Jésuite et cardinal du XVIe-XVIIe siècle, grand théologien de la Contre-Réforme. Auteur des Controverses. Docteur de l\'Église.' },
  { mmdd: '05-14', name: 'Saint Boniface de Tarse', domain: 'Martyrs',
    desc: 'Martyr romain du IIIe siècle, converti après avoir vu les miracles accomplis par les saints martyrs dont il venait recueillir les reliques.' },
  { mmdd: '05-15', name: 'Saint Jean-Baptiste de La Salle', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre et pédagogue français du XVIIe siècle, fondateur des Frères des Écoles Chrétiennes. Pionnier de l\'éducation gratuite pour les enfants pauvres.' },
  { mmdd: '05-16', name: 'Saint Ubald de Gubbio', domain: 'Évêques',
    desc: 'Évêque de Gubbio en Ombrie au XIIe siècle. Connu pour sa douceur et sa patience. Patron de Gubbio et invoqué contre les possessions démoniaques.' },
  { mmdd: '05-17', name: 'Saint Pascal Baylon', domain: 'Confesseurs',
    desc: 'Frère convers franciscain espagnol du XVIe siècle, patron des eucharisties et des congrès eucharistiques. Connu pour sa dévotion profonde au Saint-Sacrement.' },
  { mmdd: '05-18', name: 'Saint Venant de Camerino', domain: 'Martyrs',
    desc: 'Jeune martyr italien du IIIe siècle, torturé puis décapité à quinze ans pour sa foi sous le règne de Dèce. Patron de Camerino.' },
  { mmdd: '05-19', name: 'Saint Pierre Célestin', domain: 'Papes, Ermites',
    desc: 'Ermite bénédictin du XIIIe siècle, fondateur des Célestins. Élu pape en 1294, il abdiqua après cinq mois pour retourner à la vie érémitique.' },
  { mmdd: '05-20', name: 'Saint Bernardin de Sienne', domain: 'Confesseurs, Prédicateurs',
    desc: 'Franciscain italien du XVe siècle, grand prédicateur populaire. Propagea le culte du Nom de Jésus (IHS). Patron des publicitaires.' },
  { mmdd: '05-21', name: 'Sainte Hélène', domain: 'Impératrices',
    desc: 'Mère de l\'empereur Constantin au IVe siècle. Elle retrouva la vraie Croix à Jérusalem et fit construire les premiers sanctuaires chrétiens en Terre Sainte.' },
  { mmdd: '05-22', name: 'Saints Constantin et ses fils', domain: 'Empereurs',
    desc: 'Empereur Constantin le Grand, qui accorda la liberté de culte aux chrétiens par l\'édit de Milan en 313. Vénéré comme saint dans l\'Église d\'Orient.' },
  { mmdd: '05-23', name: 'Saint Didier de Vienne', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Vienne au VIIe siècle, décapité sur ordre de la reine Brunehaut pour avoir dénoncé ses mœurs dissolues. Patron de Vienne.' },
  { mmdd: '05-24', name: 'Saint Vincent de Lérins', domain: 'Confesseurs, Pères de l\'Église',
    desc: 'Moine de Lérins au Ve siècle, auteur du Commonitorium. Il formula le célèbre principe : ce qui a été cru partout, toujours et par tous.' },
  { mmdd: '05-25', name: 'Saint Grégoire VII', domain: 'Papes',
    desc: 'Pape réformateur du XIe siècle. Lutta pour la liberté de l\'Église contre le pouvoir des princes. Connu pour son combat contre l\'investiture laïque.' },
  { mmdd: '05-26', name: 'Saint Philippe Néri', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre romain du XVIe siècle, fondateur de l\'Oratoire. Connu pour sa joie, son humour et son dévouement à la jeunesse. Patron de Rome.' },
  { mmdd: '05-27', name: 'Saint Bède le Vénérable', domain: 'Docteurs, Historiens',
    desc: 'Moine bénédictin anglais du VIIIe siècle, historien de l\'Église anglaise. Auteur de l\'Histoire ecclésiastique du peuple anglais. Docteur de l\'Église.' },
  { mmdd: '05-28', name: 'Saint Augustin de Cantorbéry', domain: 'Évêques',
    desc: 'Bénédictin romain, premier archevêque de Cantorbéry au VIe siècle. Envoyé par saint Grégoire le Grand, il évangélisa l\'Angleterre anglo-saxonne.' },
  { mmdd: '05-29', name: 'Saint Maximin de Trèves', domain: 'Évêques',
    desc: 'Évêque de Trèves au IVe siècle. Accueillit saint Athanase en exil et défendit la foi orthodoxe contre les ariens. Patron de la ville de Trèves.' },
  { mmdd: '05-30', name: 'Sainte Jeanne d\'Arc', domain: 'Vierges, Héroïnes nationales',
    desc: 'Bergère de Domrémy envoyée par Dieu pour délivrer la France de l\'occupation anglaise. Brûlée vive à Rouen en 1431. Patronne secondaire de la France.' },
  { mmdd: '05-31', name: 'Sainte Pétronille', domain: 'Vierges, Martyres',
    desc: 'Vierge romaine du Ier siècle, fille spirituelle de saint Pierre selon la tradition. Patronne des papes et des filles de France.' },

  { mmdd: '06-01', name: 'Saint Fortuné de Spolète', domain: 'Martyrs',
    desc: 'Prêtre et martyr du IIIe siècle, originaire de Spolète en Ombrie. Subit le martyre sous l\'empereur Maximin pour avoir refusé de sacrifier aux idoles.' },
  { mmdd: '06-02', name: 'Saints Marcelin et Pierre', domain: 'Martyrs',
    desc: 'Prêtre et exorciste romains martyrisés sous Dioclétien au IVe siècle. Leurs reliques furent redécouvertes à Rome et leur culte est très ancien.' },
  { mmdd: '06-03', name: 'Sainte Clotilde', domain: 'Reines',
    desc: 'Épouse de Clovis, reine des Francs au VIe siècle. Elle convertit son mari au christianisme, et la France devint la fille aînée de l\'Église. Patronne des veuves.' },
  { mmdd: '06-04', name: 'Saint François Caracciolo', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre italien du XVIe siècle, fondateur des Clercs Réguliers Mineurs. Connu pour sa dévotion eucharistique et sa vie de pénitence.' },
  { mmdd: '06-05', name: 'Saint Boniface de Mayence', domain: 'Évêques, Martyrs',
    desc: 'Moine anglais, apôtre de la Germanie au VIIIe siècle. Archevêque de Mayence, martyr massacré par des païens en Frise. Patron de l\'Allemagne.' },
  { mmdd: '06-06', name: 'Saint Norbert de Xanten', domain: 'Évêques, Fondateurs',
    desc: 'Fondateur de l\'ordre des Prémontrés au XIIe siècle, archevêque de Magdebourg. Grand prédicateur itinérant, défenseur de l\'eucharistie et du célibat.' },
  { mmdd: '06-07', name: 'Saint Robert de Newminster', domain: 'Abbés',
    desc: 'Abbé cistercien anglais du XIIe siècle, fondateur des abbayes de Newminster et Pipewell. Disciple de saint Bernard, connu pour sa vie de prière.' },
  { mmdd: '06-08', name: 'Saint Médard de Noyon', domain: 'Évêques',
    desc: 'Évêque de Noyon et Tournai au VIe siècle. Protecteur des paysans et des agriculteurs. Dicton : « Quand il pleut à la Saint-Médard, il pleut quarante jours plus tard ». Patron des brasseurs.' },
  { mmdd: '06-09', name: 'Saints Prim et Félicien', domain: 'Martyrs',
    desc: 'Frères romains martyrisés sous Dioclétien au IVe siècle. Décapités pour avoir refusé d\'offrir des sacrifices aux dieux païens.' },
  { mmdd: '06-10', name: 'Sainte Marguerite d\'Écosse', domain: 'Reines',
    desc: 'Reine d\'Écosse au XIe siècle, épouse de Malcolm III. Réforma l\'Église écossaise, fonda des églises et des monastères. Patronne de l\'Écosse.' },
  { mmdd: '06-11', name: 'Saint Barnabé', domain: 'Apôtres',
    desc: 'Lévite chypriote, compagnon de saint Paul dans ses premiers voyages missionnaires. Cousin de Marc l\'Évangéliste. Fondateur de l\'Église de Chypre.' },
  { mmdd: '06-12', name: 'Saint Jean de Saint-Facond', domain: 'Confesseurs',
    desc: 'Augustin espagnol du XVe siècle. Prédicateur réputé, pacificateur des factions de Salamanque. Patron de cette ville universitaire.' },
  { mmdd: '06-13', name: 'Saint Antoine de Padoue', domain: 'Confesseurs, Docteurs',
    desc: 'Franciscain portugais du XIIIe siècle, grand prédicateur et thaumaturge. Docteur de l\'Église. Patron des pauvres et des objets perdus.' },
  { mmdd: '06-14', name: 'Saint Basile le Grand', domain: 'Évêques, Docteurs',
    desc: 'Évêque de Césarée au IVe siècle, Père cappadocien. Auteur de la règle de saint Basile, fondement du monachisme oriental.' },
  { mmdd: '06-15', name: 'Saints Modeste et Crescent', domain: 'Martyrs',
    desc: 'Martyrs du IIIe siècle, soldats de la légion thébaine selon la tradition. Persécutés sous l\'empereur Maximien pour avoir confessé leur foi.' },
  { mmdd: '06-16', name: 'Saint Jean-François Régis', domain: 'Confesseurs',
    desc: 'Jésuite français du XVIIe siècle, missionnaire dans les campagnes du Vivarais et du Velay. Connu pour son zèle apostolique et son aide aux pauvres.' },
  { mmdd: '06-17', name: 'Saint Avit', domain: 'Abbés',
    desc: 'Abbé de Micy près d\'Orléans au VIe siècle. Ermite devenu abbé, il forma de nombreux disciples. Connu pour sa science et sa sainteté.' },
  { mmdd: '06-18', name: 'Saints Marc et Marcellien', domain: 'Martyrs',
    desc: 'Frères jumeaux romains du IIIe siècle, martyrs sous Dioclétien. Refusèrent de sacrifier aux dieux malgré les supplications de leurs familles.' },
  { mmdd: '06-19', name: 'Saints Gervais et Protais', domain: 'Martyrs',
    desc: 'Frères jumeaux milanais du IIe siècle, martyrs sous Néron. Leurs reliques furent découvertes par saint Ambroise à Milan.' },
  { mmdd: '06-20', name: 'Saint Ménehould', domain: 'Vierges, Martyres',
    desc: 'Vierge et martyre du Ve siècle, originaire de la région de Châlons. Eut la tête tranchée par des barbares pour avoir refusé d\'apostasier.' },
  { mmdd: '06-21', name: 'Saint Louis de Gonzague', domain: 'Confesseurs',
    desc: 'Jésuite italien du XVIe siècle, mort à vingt-trois ans en soignant les pestiférés. Patron de la jeunesse chrétienne et des étudiants.' },
  { mmdd: '06-22', name: 'Saint Paulin de Nole', domain: 'Évêques, Confesseurs',
    desc: 'Évêque de Nole au Ve siècle. Grand poète chrétien, il convertit sa maison en monastère. Patron des cloches et des sonneurs.' },
  { mmdd: '06-23', name: 'Sainte Audrey (Edeltrude)', domain: 'Vierges, Moniales',
    desc: 'Princesse anglo-saxonne du VIIe siècle, abbesse d\'Ely. Elle conserva sa virginité dans le mariage et fonda le monastère d\'Ely. Patronne de la cathédrale d\'Ely.' },
  { mmdd: '06-24', name: 'Nativité de saint Jean-Baptiste', domain: 'Précurseur du Seigneur',
    desc: 'Naissance de Jean-Baptiste, six mois avant le Christ. Le précurseur qui baptisa Jésus au Jourdain. Solstice d\'été, fête des grands feux.' },
  { mmdd: '06-25', name: 'Saint Guillaume de Verceil', domain: 'Abbés',
    desc: 'Ermite et fondateur de l\'ordre de Montevergine au XIIe siècle. Il attira de nombreux disciples par sa sainteté et ses miracles dans le sud de l\'Italie.' },
  { mmdd: '06-26', name: 'Saints Jean et Paul', domain: 'Martyrs',
    desc: 'Deux frères officiers romains du IVe siècle, martyrisés sous Julien l\'Apostat pour avoir refusé de servir l\'armée impériale païenne.' },
  { mmdd: '06-27', name: 'Saint Ladislas de Hongrie', domain: 'Rois',
    desc: 'Roi de Hongrie au XIe siècle, défenseur de la chrétienté contre les invasions païennes. Connu pour sa piété, sa justice et sa force militaire.' },
  { mmdd: '06-28', name: 'Saint Irénée de Lyon', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Lyon au IIe siècle, disciple de Polycarpe. Auteur du Contre les Hérésies, premier grand théologien de l\'Église. Martyr.' },
  { mmdd: '06-29', name: 'Saints Pierre et Paul', domain: 'Apôtres, Piliers de l\'Église',
    desc: 'Les deux plus grands apôtres : Pierre, le premier pape, et Paul, l\'apôtre des nations. Tous deux martyrs à Rome sous Néron.' },
  { mmdd: '06-30', name: 'Commémoration de saint Paul', domain: 'Fête apostolique',
    desc: 'Commémoration spéciale de saint Paul apôtre, au lendemain de la fête des saints Pierre et Paul. Rappel de son martyre à Rome.' },

  { mmdd: '07-01', name: 'Saint Thibaut de Marly', domain: 'Abbés',
    desc: 'Abbé cistercien de Marly au XIIIe siècle, issu de la famille de Montmorency. Connu pour sa vie ascétique et sa dévotion à la Vierge Marie.' },
  { mmdd: '07-02', name: 'Visitation de la Vierge Marie', domain: 'Fête de la Vierge',
    desc: 'Marie visite sa cousine Élisabeth après l\'Annonciation. Élisabeth la salue : « Tu es bénie entre toutes les femmes ». Marie chante le Magnificat.' },
  { mmdd: '07-03', name: 'Saint Thomas', domain: 'Apôtres',
    desc: 'L\'un des douze apôtres, célèbre pour son incrédulité après la Résurrection. Il toucha les plaies du Christ et s\'écria « Mon Seigneur et mon Dieu ! ».' },
  { mmdd: '07-04', name: 'Saint Martin de Tours (ordination)', domain: 'Évêques',
    desc: 'Évêque de Tours au IVe siècle, patron de la France. Ancien soldat devenu moine, connu pour avoir partagé son manteau avec un pauvre.' },
  { mmdd: '07-05', name: 'Saint Antoine-Marie Zaccaria', domain: 'Confesseurs, Fondateurs',
    desc: 'Médecin et prêtre italien du XVIe siècle, fondateur des Barnabites. Propagea la dévotion aux Quarante-Heures et à la Croix.' },
  { mmdd: '07-06', name: 'Sainte Marie Goretti', domain: 'Vierges, Martyres',
    desc: 'Jeune fille italienne poignardée à douze ans en 1902 pour avoir défendu sa virginité. Canonisée en 1950. Modèle de pureté et de pardon.' },
  { mmdd: '07-07', name: 'Saints Cyrille et Méthode', domain: 'Évêques, Apôtres des Slaves',
    desc: 'Frères byzantins du IXe siècle, évangélisateurs des peuples slaves. Inventeurs de l\'alphabet glagolitique (ancêtre du cyrillique). Patrons de l\'Europe.' },
  { mmdd: '07-08', name: 'Sainte Élisabeth de Portugal', domain: 'Reines',
    desc: 'Reine de Portugal au XIIIe siècle. Pacificatrice et réconciliatrice, elle mit fin à plusieurs guerres civiles. Patronne du Tiers-Ordre franciscain.' },
  { mmdd: '07-09', name: 'Saint Éphrem le Syrien', domain: 'Docteurs, Poètes',
    desc: 'Diacre et poète syrien du IVe siècle. Surnommé la Harpe du Saint-Esprit pour ses hymnes et ses écrits théologiques. Docteur de l\'Église.' },
  { mmdd: '07-10', name: 'Saints Rufine et Seconde', domain: 'Martyres',
    desc: 'Sœurs romaines du IIIe siècle, martyres sous Valérien pour avoir refusé d\'épouser des païens. Leurs reliques sont conservées à Rome.' },
  { mmdd: '07-11', name: 'Saint Pie Ier', domain: 'Papes, Martyrs',
    desc: 'Pape du IIe siècle, martyr sous Marc-Aurèle. Il lutta contre les hérésies gnostiques et fixa la date de Pâques au dimanche.' },
  { mmdd: '07-12', name: 'Saint Jean Gualbert', domain: 'Abbés, Fondateurs',
    desc: 'Fondateur de l\'ordre des Vallombreuses au XIe siècle. Après avoir pardonné à l\'assassin de son frère, il se fit moine bénédictin puis fonda son propre ordre.' },
  { mmdd: '07-13', name: 'Sainte Mildrède', domain: 'Vierges, Abbesses',
    desc: 'Abbesse anglo-saxonne du VIIe siècle, petite-fille de la reine Berte. Supérieure du monastère de Minster-in-Thanet, connue pour sa sainteté.' },
  { mmdd: '07-14', name: 'Saint Bonaventure', domain: 'Évêques, Docteurs',
    desc: 'Franciscain et cardinal du XIIIe siècle, surnommé le Docteur Séraphique. Auteur de l\'Itinéraire de l\'âme à Dieu. Réforma l\'ordre franciscain.' },
  { mmdd: '07-15', name: 'Saint Henri de Bamberg', domain: 'Empereurs',
    desc: 'Empereur du Saint-Empire au XIe siècle, dernier empereur ottonien. Fondateur de l\'évêché de Bamberg. Patron des bénédictins.' },
  { mmdd: '07-16', name: 'Notre-Dame du Mont-Carmel', domain: 'Fête de la Vierge',
    desc: 'Fête de la patronne de l\'ordre du Carmel. Le scapulaire du Mont-Carmel est une dévotion mariale répandue, promettant la protection de Marie.' },
  { mmdd: '07-17', name: 'Saint Alexis', domain: 'Confesseurs',
    desc: 'Fils unique d\'un sénateur romain au Ve siècle. Il quitta tout pour vivre pauvre et inconnu, retournant mourir sous l\'escalier de la maison paternelle.' },
  { mmdd: '07-18', name: 'Saint Frédéric de Mayence', domain: 'Évêques',
    desc: 'Évêque de Mayence au Xe siècle, chancelier de l\'empire germanique. Assista à la cour d\'Otton Ier et participa à l\'organisation de l\'Église impériale.' },
  { mmdd: '07-19', name: 'Saint Vincent de Paul', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre français du XVIIe siècle, fondateur des Lazaristes et des Filles de la Charité. Patron de toutes les œuvres de charité et des prisonniers.' },
  { mmdd: '07-20', name: 'Sainte Marguerite d\'Antioche', domain: 'Vierges, Martyres',
    desc: 'Vierge et martyre du IVe siècle. Selon la tradition, elle vainquit un dragon figure du démon. Patronne des femmes enceintes.' },
  { mmdd: '07-21', name: 'Saint Victor de Marseille', domain: 'Martyrs',
    desc: 'Soldat romain martyrisé à Marseille au IVe siècle sous Maximien. Refusa de sacrifier aux idoles et fut écrasé entre deux meules. Grand saint de la Provence.' },
  { mmdd: '07-22', name: 'Sainte Marie-Madeleine', domain: 'Pénitentes',
    desc: 'Disciple du Christ, présente au pied de la Croix et première témoin de la Résurrection. Patronne de la Provence. Sa légende dorée l\'associe à la Sainte-Baume.' },
  { mmdd: '07-23', name: 'Saint Apollinaire de Ravenne', domain: 'Évêques, Martyrs',
    desc: 'Premier évêque de Ravenne au IIe siècle, disciple de saint Pierre. Martyr sous Vespasien, il subit de nombreux supplices avant d\'être décapité.' },
  { mmdd: '07-24', name: 'Sainte Christine de Tyr', domain: 'Vierges, Martyres',
    desc: 'Vierge et martyre du IVe siècle. Torturée par son père gouverneur puis livrée à d\'autres supplices, elle mourut percée de flèches.' },
  { mmdd: '07-25', name: 'Saint Jacques le Majeur', domain: 'Apôtres',
    desc: 'Apôtre et martyr, frère de Jean l\'Évangéliste. Premier apôtre à subir le martyre, décapité par Hérode Agrippa. Patron de l\'Espagne et de Compostelle.' },
  { mmdd: '07-26', name: 'Sainte Anne et saint Joachim', domain: 'Parents de la Vierge',
    desc: 'Parents de la Vierge Marie et grands-parents de Jésus. Patrons des grands-parents, des mères de famille et des marins. Leur culte est très populaire en France.' },
  { mmdd: '07-27', name: 'Saint Pantaléon', domain: 'Martyrs',
    desc: 'Médecin de Nicomédie au IVe siècle, martyr sous Dioclétien. Patron des médecins et des pharmaciens. L\'un des quatorze saints auxiliateurs.' },
  { mmdd: '07-28', name: 'Saint Samson de Dol', domain: 'Évêques',
    desc: 'Moine gallois du VIe siècle, l\'un des sept saints fondateurs de la Bretagne armoricaine. Premier évêque de Dol-de-Bretagne.' },
  { mmdd: '07-29', name: 'Sainte Marthe', domain: 'Veuves, Hôtesses',
    desc: 'Sœur de Lazare et de Marie de Béthanie. Celle qui servait Jésus à table et crut en lui lors de la résurrection de son frère. Patronne des cuisinières.' },
  { mmdd: '07-30', name: 'Saint Pierre Chrysologue', domain: 'Évêques, Docteurs',
    desc: 'Évêque de Ravenne au Ve siècle. Surnommé Parole d\'or pour ses homélies vibrantes. Docteur de l\'Église, ses sermons sont des classiques de la patristique.' },
  { mmdd: '07-31', name: 'Saint Ignace de Loyola', domain: 'Confesseurs, Fondateurs',
    desc: 'Gentilhomme basque fondateur de la Compagnie de Jésus (Jésuites) au XVIe siècle. Auteur des Exercices Spirituels. Patron des retraites et de Bilbao.' },

  { mmdd: '08-01', name: 'Saint Pierre-aux-Liens', domain: 'Fête apostolique',
    desc: 'Commémoration des chaînes de saint Pierre à Rome et de sa délivrance miraculeuse par un ange. Fête célébrée dans la basilique Saint-Pierre-aux-Liens.' },
  { mmdd: '08-02', name: 'Saint Alphonse de Liguori', domain: 'Évêques, Docteurs',
    desc: 'Fondateur des Rédemptoristes au XVIIIe siècle, évêque et moraliste. Auteur de la Théologie morale. Docteur de l\'Église. Patron des confesseurs.' },
  { mmdd: '08-03', name: 'Invention de saint Étienne', domain: 'Découverte de reliques',
    desc: 'Découverte des reliques du premier martyr saint Étienne à Jérusalem en 415. Ses reliques furent dispersées dans le monde chrétien.' },
  { mmdd: '08-04', name: 'Saint Dominique', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'ordre des Prêcheurs (Dominicains) au XIIIe siècle. Grand prédicateur contre l\'hérésie cathare. Propagea le rosaire.' },
  { mmdd: '08-05', name: 'Notre-Dame des Neiges', domain: 'Fête de la Vierge',
    desc: 'Fête de la dédicace de la basilique Sainte-Marie-Majeure à Rome. Une neige miraculeuse tomba sur l\'Esquilin en plein été pour indiquer l\'emplacement de l\'église.' },
  { mmdd: '08-06', name: 'Transfiguration du Seigneur', domain: 'Fête du Seigneur',
    desc: 'Jésus se transfigura sur le mont Thabor devant Pierre, Jacques et Jean. Son visage devint éclatant comme le soleil et ses vêtements blancs comme la lumière.' },
  { mmdd: '08-07', name: 'Saint Gaëtan de Thiene', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre italien du XVIe siècle, cofondateur des Théatins. Connu pour sa confiance totale en la Providence et son service des pauvres.' },
  { mmdd: '08-08', name: 'Saints Cyriaque, Largus et Smaragde', domain: 'Martyrs',
    desc: 'Martyrs romains du IVe siècle. Cyriaque était diacre, Largus et Smaragde ses compagnons. Leurs reliques sont vénérées dans la catacombe de Sainte-Cyriaque.' },
  { mmdd: '08-09', name: 'Saint Jean Vianney', domain: 'Confesseurs',
    desc: 'Curé d\'Ars au XIXe siècle, modèle des curés de campagne. Confesseur infatigable, il passait jusqu\'à 18 heures par jour au confessionnal. Patron des prêtres.' },
  { mmdd: '08-10', name: 'Saint Laurent', domain: 'Diacres, Martyrs',
    desc: 'Diacre de Rome, martyrisé sur un gril en 258 sous Valérien. « Je suis cuit, retourne-moi ! » dit-il au bourreau. Patron des bibliothécaires et des cuisiniers.' },
  { mmdd: '08-11', name: 'Sainte Claire d\'Assise', domain: 'Vierges, Fondatrices',
    desc: 'Compagne de saint François, fondatrice des Clarisses au XIIIe siècle. Patronne de la télévision (visions mystiques). Protectrice de ceux qui ont mal aux yeux.' },
  { mmdd: '08-12', name: 'Sainte Claire de Montefalco', domain: 'Vierges, Abbesses',
    desc: 'Abbesse augustine italienne du XIVe siècle. Connue pour sa dévotion à la Passion du Christ et les stigmates de la Croix qu\'elle portait dans son cœur.' },
  { mmdd: '08-13', name: 'Saint Hippolyte et saint Pontien', domain: 'Papes, Martyrs',
    desc: 'Hippolyte, antipape puis martyr, et Pontien, pape. Tous deux déportés en Sardaigne par l\'empereur Maxime et morts de mauvais traitements.' },
  { mmdd: '08-14', name: 'Saint Eusèbe de Rome', domain: 'Prêtres, Confesseurs',
    desc: 'Prêtre romain du IVe siècle, emprisonné par l\'empereur Constance pour avoir défendu la divinité du Christ contre les ariens. Mort en prison.' },
  { mmdd: '08-15', name: 'Assomption de la Vierge Marie', domain: 'Fête de la Vierge',
    desc: 'La Vierge Marie est élevée corps et âme au ciel au terme de sa vie terrestre. Dogme depuis 1850. La plus grande fête mariale, jour férié en France.' },
  { mmdd: '08-16', name: 'Saint Roch', domain: 'Confesseurs',
    desc: 'Pèlerin et thaumaturge du XIVe siècle. Connu pour avoir guéri les pestiférés en se signant du signe de croix. Patron des médecins et des pèlerins.' },
  { mmdd: '08-17', name: 'Saint Hyacinthe', domain: 'Confesseurs, Missionnaires',
    desc: 'Dominicain polonais du XIIIe siècle, missionnaire en Pologne, Ruthénie et Prusse. Apôtre du Nord de l\'Europe. Patron de la Pologne.' },
  { mmdd: '08-18', name: 'Sainte Jeanne de Chantal', domain: 'Veuves, Fondatrices',
    desc: 'Fondatrice de l\'ordre de la Visitation au XVIIe siècle avec saint François de Sales. Mère de famille devenue religieuse. Patronne des veuves.' },
  { mmdd: '08-19', name: 'Saint Louis de Toulouse', domain: 'Évêques',
    desc: 'Évêque franciscain de Toulouse au XIVe siècle, fils de Charles II d\'Anjou. Renaça au trône de Naples pour entrer dans l\'ordre de saint François.' },
  { mmdd: '08-20', name: 'Saint Bernard de Clairvaux', domain: 'Abbés, Docteurs',
    desc: 'Abbé cistercien du XIIe siècle, grand mystique et prédicateur de la deuxième croisade. Docteur de l\'Église. Surnommé le Docteur Melliflue.' },
  { mmdd: '08-21', name: 'Sainte Jeanne de France', domain: 'Reines, Fondatrices',
    desc: 'Fille de Louis XI, reine de France puis répudiée. Fondatrice de l\'ordre des Annonciades au XVIe siècle. Patronne de la France.' },
  { mmdd: '08-22', name: 'Saints Symphorien et Timothée', domain: 'Martyrs',
    desc: 'Symphorien, jeune martyr d\'Autun au IIe siècle sous Marc-Aurèle, décapité pour sa foi. C\'est le premier martyr de Gaule. Timothée fut son compagnon.' },
  { mmdd: '08-23', name: 'Saint Philippe Bénit', domain: 'Confesseurs',
    desc: 'Servite italien du XIIIe siècle, général de l\'ordre des Servites de Marie. Connu pour sa douceur, sa patience et ses miracles.' },
  { mmdd: '08-24', name: 'Saint Barthélemy', domain: 'Apôtres',
    desc: 'Apôtre du Christ, évangélisateur de l\'Arménie. Mort écorché vif et crucifié par les païens. Patron des bouchers et des tanneurs.' },
  { mmdd: '08-25', name: 'Saint Louis', domain: 'Rois, Confesseurs',
    desc: 'Roi de France au XIIIe siècle, modèle du roi chrétien. Bâtisseur de la Sainte-Chapelle, croisé, juste et pieux. Patron de la France.' },
  { mmdd: '08-26', name: 'Saint Zéphyrin', domain: 'Papes, Martyrs',
    desc: 'Pape du IIIe siècle, martyr sous Sévère. Gouverna l\'Église pendant vingt ans et lutta contre les hérésies de son temps.' },
  { mmdd: '08-27', name: 'Saint Joseph Calasanz', domain: 'Confesseurs, Fondateurs',
    desc: 'Prêtre espagnol du XVIIe siècle, fondateur des Écoles Pies. Pionnier de l\'éducation populaire gratuite. Patron des écoles chrétiennes.' },
  { mmdd: '08-28', name: 'Saint Augustin d\'Hippone', domain: 'Évêques, Docteurs',
    desc: 'Évêque d\'Hippone en Afrique du Nord au Ve siècle. Le plus grand Père de l\'Église latine, auteur des Confessions et de la Cité de Dieu.' },
  { mmdd: '08-29', name: 'Décollation de saint Jean-Baptiste', domain: 'Martyrs',
    desc: 'Commémoration de la décapitation de Jean-Baptiste sur ordre d\'Hérode Antipas, pour avoir dénoncé son mariage illégitime avec Hérodiade.' },
  { mmdd: '08-30', name: 'Sainte Rose de Lima', domain: 'Vierges',
    desc: 'Première sainte de l\'Amérique latine au XVIIe siècle. Tertiaire dominicaine péruvienne, mena une vie de pénitence et de service des pauvres.' },
  { mmdd: '08-31', name: 'Saint Raymond Nonnat', domain: 'Confesseurs',
    desc: 'Cardinal espagnol du XIIIe siècle, de l\'ordre de la Merci. Racheta des captifs en Afrique du Nord. Patron des sage-femmes et des nouveau-nés.' },

  { mmdd: '09-01', name: 'Saint Gilles', domain: 'Abbés, Ermites',
    desc: 'Ermite provençal du VIIe siècle, l\'un des quatorze saints auxiliateurs. Fondateur de l\'abbaye de Saint-Gilles-du-Gard. Patron des mendiants et des infirmes.' },
  { mmdd: '09-02', name: 'Saint Étienne de Hongrie', domain: 'Rois',
    desc: 'Premier roi de Hongrie au XIe siècle, qui convertit son peuple au christianisme. Patron de la Hongrie. Couronné par le pape Sylvestre II.' },
  { mmdd: '09-03', name: 'Saint Grégoire le Grand', domain: 'Papes, Docteurs',
    desc: 'Pape au VIe siècle. Envoya des missionnaires évangéliser l\'Angleterre et réforma la liturgie et le chant. Grand pontife et père de l\'Église médiévale.' },
  { mmdd: '09-04', name: 'Sainte Rose de Viterbe', domain: 'Vierges',
    desc: 'Jeune fille franciscaine italienne du XIIIe siècle. Prêcha dans les rues de Viterbe contre l\'empereur Frédéric II. Morte à dix-huit ans.' },
  { mmdd: '09-05', name: 'Saint Laurent Justinien', domain: 'Évêques',
    desc: 'Premier patriarche de Venise au XVe siècle. Moine augustin, il devint évêque de Venise et réforma le clergé.' },
  { mmdd: '09-06', name: 'Saint Éleuthère de Spolète', domain: 'Martyrs',
    desc: 'Abbé et martyr du VIe siècle, originaire de Spolète. Mis à mort par les Lombards païens pour avoir défendu la foi chrétienne.' },
  { mmdd: '09-07', name: 'Saint Cloud', domain: 'Confesseurs',
    desc: 'Petit-fils de Clovis, devenu ermite puis prêtre. Fondateur du monastère de Saint-Cloud près de Paris. Patron des cloutiers.' },
  { mmdd: '09-08', name: 'Nativité de la Vierge Marie', domain: 'Fête de la Vierge',
    desc: 'Naissance de la Vierge Marie, neuf mois après l\'Immaculée Conception. Fête joyeuse qui ouvre le cycle de la Nativité du Christ.' },
  { mmdd: '09-09', name: 'Saint Gorgon', domain: 'Martyrs',
    desc: 'Soldat romain du IVe siècle, martyr sous Dioclétien. Ses reliques furent transportées en Gaule et son culte se répandit dans toute l\'Europe franque.' },
  { mmdd: '09-10', name: 'Saint Nicolas de Tolentino', domain: 'Confesseurs',
    desc: 'Augustin italien du XIIIe siècle, grand prédicateur et thaumaturge. Connu pour ses guérisons miraculeuses et la bénédiction du pain de saint Nicolas.' },
  { mmdd: '09-11', name: 'Saints Prothe et Hyacinthe', domain: 'Martyrs',
    desc: 'Frères martyrs romains du IIIe siècle, eunuques de la cour de sainte Eugénie. Décapités pour leur foi sous Valérien.' },
  { mmdd: '09-12', name: 'Saint Gui de Courtrai', domain: 'Confesseurs',
    desc: 'Moine cistercien flamand du XIIIe siècle, abbé de Ter Doest. Connu pour sa science et sa sainteté.' },
  { mmdd: '09-13', name: 'Saint Philippe d\'Hélène', domain: 'Martyrs',
    desc: 'Martyr romain du IIIe siècle sous l\'empereur Dèce. Refusa d\'offrir des sacrifices aux dieux et fut décapité.' },
  { mmdd: '09-14', name: 'Exaltation de la Sainte Croix', domain: 'Fête du Seigneur',
    desc: 'Fête de la Croix glorieuse du Christ. Commémore la dédicace des basiliques du Calvaire et de la Résurrection à Jérusalem en 335.' },
  { mmdd: '09-15', name: 'Octave de la Nativité de la Vierge', domain: 'Fête de la Vierge',
    desc: 'Huitième jour après la Nativité de la Vierge Marie. Dans l\'ancien calendrier, l\'octave prolongeait la solennité mariale.' },
  { mmdd: '09-16', name: 'Saint Cyprien de Carthage', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Carthage au IIIe siècle, grand Père de l\'Église africaine. Auteur de l\'Unité de l\'Église. Martyr sous Valérien.' },
  { mmdd: '09-17', name: 'Saint Lambert de Maastricht', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Maastricht au VIIIe siècle, martyr assassiné pour avoir défendu la morale chrétienne contre les excès du pouvoir civil.' },
  { mmdd: '09-18', name: 'Saint Joseph de Cupertino', domain: 'Confesseurs',
    desc: 'Franciscain italien du XVIIe siècle, connu pour ses lévitations mystiques pendant la prière. Patron des candidats aux examens et des aviateurs.' },
  { mmdd: '09-19', name: 'Saint Janvier de Naples', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Bénévent au IVe siècle, martyr sous Dioclétien. Le miracle de son sang (liquéfaction) a lieu trois fois par an à Naples.' },
  { mmdd: '09-20', name: 'Saint Eustache et ses compagnons', domain: 'Martyrs',
    desc: 'Général romain du IIe siècle, converti avec sa famille. Martyr brûlé vif dans un taureau d\'airain. L\'un des quatorze saints auxiliateurs.' },
  { mmdd: '09-21', name: 'Saint Matthieu', domain: 'Apôtres, Évangélistes',
    desc: 'Apôtre et évangéliste, publicain (collecteur d\'impôts) appelé par Jésus. Auteur du premier évangile. Patron des banquiers et des comptables.' },
  { mmdd: '09-22', name: 'Saint Maurice et la Légion Thébaine', domain: 'Martyrs',
    desc: 'Soldats de la légion thébaine, massacrés à Agaune (aujourd\'hui Saint-Maurice en Valais) pour avoir refusé de sacrifier aux dieux sous Maximien.' },
  { mmdd: '09-23', name: 'Sainte Thècle', domain: 'Vierges, Martyres',
    desc: 'Disciples de saint Paul à Iconium, première vierge martyre de l\'Église. Sauvée miraculeusement du bûcher et des bêtes. Patronne de Catalogne.' },
  { mmdd: '09-24', name: 'Notre-Dame de la Merci', domain: 'Fête de la Vierge',
    desc: 'Fête de la Vierge Marie sous le titre de la Merci (Miséricorde). Patronne de l\'ordre de la Merci fondé pour le rachat des captifs.' },
  { mmdd: '09-25', name: 'Saint Firmin d\'Amiens', domain: 'Évêques, Martyrs',
    desc: 'Premier évêque d\'Amiens au IIIe siècle, martyr décapité. Ses reliques furent retrouvées au VIIe siècle. Patron de la ville d\'Amiens.' },
  { mmdd: '09-26', name: 'Saints Cyprien et Justine', domain: 'Martyrs',
    desc: 'Martyrs d\'Antioche au IVe siècle. Cyprien, magicien converti, et Justine, vierge qu\'il avait tenté de séduire. Tous deux décapités sous Dioclétien.' },
  { mmdd: '09-27', name: 'Saints Côme et Damien', domain: 'Martyrs, Médecins',
    desc: 'Frères médecins syriens du IIIe siècle, martyrs sous Dioclétien. Patrons des médecins, des chirurgiens et des pharmaciens.' },
  { mmdd: '09-28', name: 'Saint Venceslas de Bohême', domain: 'Martyrs, Princes',
    desc: 'Duc de Bohême au Xe siècle, assassiné par son frère pour sa foi chrétienne. Patron de la République tchèque. Modèle du souverain chrétien.' },
  { mmdd: '09-29', name: 'Saint Michel Archange', domain: 'Archanges',
    desc: 'Prince des anges, vainqueur de Satan. Chef des armées célestes, protecteur d\'Israël et gardien du Paradis. Patron de la France et de la gendarmerie.' },
  { mmdd: '09-30', name: 'Saint Jérôme', domain: 'Docteurs, Traducteurs',
    desc: 'Père de l\'Église au Ve siècle, traducteur de la Bible en latin (Vulgate). Moine ascétique, exégète et grand savant. Patron des traducteurs.' },

  { mmdd: '10-01', name: 'Saint Rémi de Reims', domain: 'Évêques',
    desc: 'Évêque de Reims au VIe siècle. Il baptisa Clovis, roi des Francs, le jour de Noël 496. Patron de la France et de l\'archidiocèse de Reims.' },
  { mmdd: '10-02', name: 'Saints Anges Gardiens', domain: 'Anges',
    desc: 'Fête des saints anges gardiens instituée au XVIIe siècle. Chaque chrétien a un ange protecteur qui l\'accompagne tout au long de sa vie.' },
  { mmdd: '10-03', name: 'Saint Gérard de Brogne', domain: 'Abbés',
    desc: 'Abbé belge du Xe siècle, réformateur du monachisme bénédictin dans les Pays-Bas. Fondateur de l\'abbaye de Brogne.' },
  { mmdd: '10-04', name: 'Saint François d\'Assise', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'ordre franciscain au XIIIe siècle. Pauvre parmi les pauvres, il prêchait aux oiseaux et aux bêtes. Patron de l\'Italie et des animaux.' },
  { mmdd: '10-05', name: 'Sainte Fleur d\'Issendolus', domain: 'Vierges, Moniales',
    desc: 'Moniale française du XIVe siècle, prieure du couvent d\'Issendolus dans le Lot. Connue pour ses stigmates et sa dévotion eucharistique.' },
  { mmdd: '10-06', name: 'Saint Bruno', domain: 'Confesseurs, Fondateurs',
    desc: 'Fondateur de l\'ordre des Chartreux au XIe siècle. Chanoine de Cologne devenu ermite dans le désert de Chartreuse. Patron des ermites.' },
  { mmdd: '10-07', name: 'Notre-Dame du Rosaire', domain: 'Fête de la Vierge',
    desc: 'Fête instituée par saint Pie V après la victoire de Lépante (1571). La Vierge Marie est honorée sous le titre du Rosaire, prière méditative des mystères du Christ.' },
  { mmdd: '10-08', name: 'Sainte Pélagie la Pénitente', domain: 'Pénitentes',
    desc: 'Comédienne d\'Antioche convertie au Ve siècle. Après une vie de péché, elle fit pénitence comme ermite sur le Mont des Oliviers.' },
  { mmdd: '10-09', name: 'Saint Denis et ses compagnons', domain: 'Martyrs, Patron de Paris',
    desc: 'Premier évêque de Paris, martyrisé avec Rustique et Éleuthère au IIIe siècle. Porta sa tête tranchée jusqu\'à Montmartre. Patron de Paris.' },
  { mmdd: '10-10', name: 'Saint Ghislain', domain: 'Ermites, Fondateurs',
    desc: 'Ermite belge du VIIe siècle, fondateur du monastère de Saint-Ghislain dans le Hainaut. Patron des marins et des bateliers.' },
  { mmdd: '10-11', name: 'Saint Firmin d\'Uzès', domain: 'Évêques',
    desc: 'Évêque d\'Uzès au VIe siècle. Disciple de saint Benoît, il introduisit la règle bénédictine en Gaule et fonda plusieurs monastères.' },
  { mmdd: '10-12', name: 'Saint Wilfrid d\'York', domain: 'Évêques',
    desc: 'Évêque d\'York au VIIe siècle. Apôtre du Sussex, il introduisit en Angleterre la règle de saint Benoît et la liturgie romaine.' },
  { mmdd: '10-13', name: 'Saint Édouard le Confesseur', domain: 'Rois',
    desc: 'Roi d\'Angleterre au XIe siècle. Connu pour sa piété, sa justice et sa chasteté. Fit construire l\'abbaye de Westminster où il est enterré.' },
  { mmdd: '10-14', name: 'Saint Calliste Ier', domain: 'Papes, Martyrs',
    desc: 'Pape du IIIe siècle, martyr sous Alexandre Sévère. Organisa les catacombes de Rome et lutta contre les hérésies.' },
  { mmdd: '10-15', name: 'Sainte Thérèse d\'Avila', domain: 'Vierges, Docteurs',
    desc: 'Réformatrice du Carmel au XVIe siècle, mystique et docteur de l\'Église. Auteur du Château intérieur. Patronne des écrivains et des Espagne.' },
  { mmdd: '10-16', name: 'Sainte Edwige de Silésie', domain: 'Veuves, Duchesses',
    desc: 'Duchesse de Silésie au XIIIe siècle. Entrée au monastère de Trebnitz après la mort de son époux. Patronne de la Silésie.' },
  { mmdd: '10-17', name: 'Saint Ignace d\'Antioche', domain: 'Évêques, Martyrs',
    desc: 'Évêque d\'Antioche au IIe siècle, disciple de saint Jean. Condamné aux bêtes à Rome, il écrivit sept lettres fameuses sur le chemin de son martyre.' },
  { mmdd: '10-18', name: 'Saint Luc l\'Évangéliste', domain: 'Évangélistes',
    desc: 'Médecin d\'Antioche, compagnon de saint Paul. Auteur du troisième évangile et des Actes des Apôtres. Patron des médecins et des artistes.' },
  { mmdd: '10-19', name: 'Saint Pierre d\'Alcantara', domain: 'Confesseurs',
    desc: 'Franciscain espagnol du XVIe siècle, réformateur de l\'ordre (Alcantarins). Conseiller de sainte Thérèse d\'Avila, connu pour son austérité.' },
  { mmdd: '10-20', name: 'Saint Jean de Kenty', domain: 'Confesseurs',
    desc: 'Prêtre polonais du XVe siècle, professeur à l\'université de Cracovie. Connu pour sa charité et sa piété. Patron de la Pologne.' },
  { mmdd: '10-21', name: 'Sainte Ursule et ses compagnes', domain: 'Vierges, Martyres',
    desc: 'Vierge britannique du IVe siècle, martyrisée à Cologne avec onze mille compagnes par les Huns. Patronne des éducatrices et des jeunes filles.' },
  { mmdd: '10-22', name: 'Saint Vallier de Langres', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Langres au IVe siècle, martyrisé par les Vandales pour avoir défendu sa foi. L\'un des saints les plus vénérés de Bourgogne.' },
  { mmdd: '10-23', name: 'Saint Jean de Capistran', domain: 'Confesseurs',
    desc: 'Franciscain italien du XVe siècle, grand prédicateur et inquisiteur. Organisa la défense de Belgrade contre les Turcs.' },
  { mmdd: '10-24', name: 'Saint Martin de Vertou', domain: 'Abbés',
    desc: 'Moine et abbé du VIIe siècle, évangélisateur de la région de Nantes. Fondateur de l\'abbaye de Vertou. Connu pour ses nombreux miracles.' },
  { mmdd: '10-25', name: 'Saints Chrysanthe et Darie', domain: 'Martyrs',
    desc: 'Époux romains du IIIe siècle, martyrisés sous Numérien. Chrysanthe, patricien converti, épousa Darie, vestale, qu\'il convertit à son tour.' },
  { mmdd: '10-26', name: 'Saint Évariste', domain: 'Papes, Martyrs',
    desc: 'Pape du IIe siècle, martyr sous Trajan. D\'origine grecque, il succéda à saint Clément et organisa le clergé de Rome.' },
  { mmdd: '10-27', name: 'Saint Frumence d\'Axoum', domain: 'Évêques',
    desc: 'Évêque et apôtre de l\'Éthiopie au IVe siècle. Après un naufrage en mer Rouge, il évangélisa la cour du roi d\'Axoum.' },
  { mmdd: '10-28', name: 'Saints Simon et Jude', domain: 'Apôtres',
    desc: 'Deux des douze apôtres. Simon le Zélote évangélisa la Perse, Jude (Thaddée) l\'Égypte. Tous deux martyrs. Jude est le patron des causes désespérées.' },
  { mmdd: '10-29', name: 'Saint Narcisse de Jérusalem', domain: 'Évêques',
    desc: 'Évêque de Jérusalem au IIIe siècle. Il vécut plus de cent seize ans et opéra de nombreux miracles, dont l\'eau changée en huile pour les lampes de Pâques.' },
  { mmdd: '10-30', name: 'Saint Marcel du Centre', domain: 'Martyrs',
    desc: 'Centurion romain de la Légion de Trajane, martyr à Tanger au IIIe siècle pour avoir refusé de servir sous l\'empereur païen et jeté son bâton de commandement.' },
  { mmdd: '10-31', name: 'Saint Quentin', domain: 'Martyrs',
    desc: 'Missionnaire romain, martyr dans le Vermandois au IIIe siècle sous Maximien. Patron de la ville de Saint-Quentin.' },

  { mmdd: '11-01', name: 'Toussaint', domain: 'Fête de tous les saints',
    desc: 'Fête de tous les saints du ciel, connus et inconnus. Instituée au VIIIe siècle par le pape Grégoire IV. L\'une des plus grandes fêtes de l\'année liturgique.' },
  { mmdd: '11-02', name: 'Commémoration des fidèles défunts', domain: 'Fête des morts',
    desc: 'Jour de prière pour tous les morts institué par Odon de Cluny au Xe siècle. Grand jour de visite des cimetières et de prières pour les défunts.' },
  { mmdd: '11-03', name: 'Saint Hubert', domain: 'Évêques',
    desc: 'Évêque de Liège au VIIIe siècle, apôtre de l\'Ardenne. Converti miraculeusement par un cerf portant une croix entre ses bois. Patron des chasseurs.' },
  { mmdd: '11-04', name: 'Saint Charles Borromée', domain: 'Évêques',
    desc: 'Archevêque de Milan au XVIe siècle, figure de proue de la Contre-Réforme. Réforma l\'Église, soigna les pestiférés. Patron des séminaristes.' },
  { mmdd: '11-05', name: 'Sainte Bertille', domain: 'Vierges, Abbesses',
    desc: 'Abbesse du monastère de Chelles au VIIe siècle, disciple de sainte Bathilde. Réforma plusieurs monastères de Gaule.' },
  { mmdd: '11-06', name: 'Saint Léonard de Noblat', domain: 'Ermites',
    desc: 'Ermite limousin du VIe siècle, disciple de saint Rémi. Protecteur des prisonniers et des captifs. Patron des serruriers.' },
  { mmdd: '11-07', name: 'Saint Willibrord d\'Utrecht', domain: 'Évêques',
    desc: 'Moine anglo-saxon du VIIe siècle, apôtre de la Frise et des Pays-Bas. Archevêque d\'Utrecht. Fondateur de l\'abbaye d\'Echternach.' },
  { mmdd: '11-08', name: 'Saints Quatre Couronnés', domain: 'Martyrs',
    desc: 'Quatre soldats romains du IVe siècle, martyrs pour avoir refusé de sculpter une idole païenne. Patrons des sculpteurs et des tailleurs de pierre.' },
  { mmdd: '11-09', name: 'Dédicace de l\'archibasilique du Latran', domain: 'Fête de l\'Église',
    desc: 'Anniversaire de la dédicace de la basilique Saint-Jean-de-Latran, cathédrale de Rome et mère de toutes les églises du monde.' },
  { mmdd: '11-10', name: 'Saint Léon le Grand', domain: 'Papes, Docteurs',
    desc: 'Pape du Ve siècle qui arrêta Attila et formula la doctrine de l\'Incarnation à Chalcédoine. Grand docteur de l\'Église et Père de la chrétienté.' },
  { mmdd: '11-11', name: 'Saint Martin de Tours', domain: 'Évêques',
    desc: 'Évêque de Tours au IVe siècle, patron de la France. Ancien soldat devenu moine, il partagea son manteau avec un pauvre à Amiens. Fête des vendanges.' },
  { mmdd: '11-12', name: 'Saint Josse', domain: 'Ermites',
    desc: 'Prince breton du VIIe siècle, ermite dans le Ponthieu où il fonda le village de Saint-Josse-sur-Mer. Patron des pèlerins.' },
  { mmdd: '11-13', name: 'Saint Brice de Tours', domain: 'Évêques',
    desc: 'Évêque de Tours au Ve siècle, successeur de saint Martin. Jeune élève turbulent de Martin, il devint par la suite un saint évêque exemplaire.' },
  { mmdd: '11-14', name: 'Saint Laurent O\'Toole', domain: 'Évêques',
    desc: 'Archevêque de Dublin au XIIe siècle. Réforma l\'Église irlandaise après l\'invasion normande. Mort à Eu en Normandie.' },
  { mmdd: '11-15', name: 'Saint Malachie d\'Armagh', domain: 'Évêques',
    desc: 'Archevêque d\'Armagh au XIIe siècle, grand réformateur de l\'Église d\'Irlande. Connu pour ses prophéties sur les papes.' },
  { mmdd: '11-16', name: 'Sainte Marguerite d\'Écosse', domain: 'Reines',
    desc: 'Reine d\'Écosse au XIe siècle, épouse de Malcolm III. Convertit le peuple écossais, fonda des églises et des monastères.' },
  { mmdd: '11-17', name: 'Saint Grégoire le Thaumaturge', domain: 'Évêques',
    desc: 'Évêque de Néocésarée au IIIe siècle. Surnommé le Faiseur de miracles pour les nombreux prodiges accomplis pendant son épiscopat.' },
  { mmdd: '11-18', name: 'Dédicace des basiliques de Pierre et Paul', domain: 'Fête apostolique',
    desc: 'Anniversaire de la dédicace des basiliques de saint Pierre au Vatican et de saint Paul-hors-les-murs à Rome, fondations de la chrétienté.' },
  { mmdd: '11-19', name: 'Sainte Élisabeth de Hongrie', domain: 'Veuves, Tertiaires',
    desc: 'Princesse hongroise du XIIIe siècle, veuve à vingt ans. Distribua ses biens aux pauvres et servit les malades. Patronne du Tiers-Ordre franciscain.' },
  { mmdd: '11-20', name: 'Saint Félix de Valois', domain: 'Confesseurs',
    desc: 'Co-fondateur de l\'Ordre des Trinitaires au XIIe siècle. Ermite dans le Valois, il consacra sa vie au rachat des captifs.' },
  { mmdd: '11-21', name: 'Présentation de la Vierge Marie', domain: 'Fête de la Vierge',
    desc: 'Présentation de Marie au Temple par ses parents Anne et Joachim. La Vierge enfant fut consacrée à Dieu dans le Temple de Jérusalem.' },
  { mmdd: '11-22', name: 'Sainte Cécile', domain: 'Vierges, Martyres',
    desc: 'Jeune romaine du IIIe siècle, vierge et martyre. Patronne de la musique et des musiciens. « Cantantibus organis, Caecilia Domino decantabat ».' },
  { mmdd: '11-23', name: 'Saint Clément Ier', domain: 'Papes, Martyrs',
    desc: 'Troisième pape après Pierre, évêque de Rome au Ier siècle. Auteur de l\'Épître aux Corinthiens. Martyr exilé en Crimée.' },
  { mmdd: '11-24', name: 'Saint Jean de la Croix', domain: 'Docteurs, Mystiques',
    desc: 'Réformateur du Carmel au XVIe siècle, poète mystique. Auteur de La Nuit obscure et du Cantique spirituel. Docteur de l\'Église.' },
  { mmdd: '11-25', name: 'Sainte Catherine d\'Alexandrie', domain: 'Vierges, Martyres',
    desc: 'Vierge savante d\'Égypte, martyrisée au IVe siècle sur une roue à pointes. Patronne des philosophes et des jeunes filles. Fête des jeunes filles célibataires.' },
  { mmdd: '11-26', name: 'Saint Sylvestre Gozzolini', domain: 'Abbés, Fondateurs',
    desc: 'Fondateur de la congrégation bénédictine des Sylvestrins au XIIIe siècle. Abbé italien, réformateur de la vie monastique.' },
  { mmdd: '11-27', name: 'Saint Séverin de Paris', domain: 'Ermites, Confesseurs',
    desc: 'Ermite parisien du VIe siècle, vécut sur la rive gauche de la Seine. Ses prières sauvèrent Paris d\'un incendie.' },
  { mmdd: '11-28', name: 'Saint Jacques de la Marche', domain: 'Confesseurs',
    desc: 'Franciscain italien du XVe siècle, grand prédicateur itinérant. Lutta contre l\'usure et fonda les monts-de-piété.' },
  { mmdd: '11-29', name: 'Saint Saturnin de Toulouse', domain: 'Évêques, Martyrs',
    desc: 'Premier évêque de Toulouse au IIIe siècle. Martyrisé par les païens qui l\'attachèrent à un taureau furieux. Patron de Toulouse.' },
  { mmdd: '11-30', name: 'Saint André', domain: 'Apôtres',
    desc: 'Apôtre, frère de saint Pierre. Évangélisa la Grèce et la Scythie. Crucifié sur une croix en X (croix de saint André). Patron de l\'Écosse et de la Russie.' },

  { mmdd: '12-01', name: 'Saint Éloi', domain: 'Évêques',
    desc: 'Évêque de Noyon au VIIe siècle, grand orfèvre et monétaire du roi Dagobert. Patron des orfèvres, des bijoutiers et des mécaniciens.' },
  { mmdd: '12-02', name: 'Sainte Bibiane', domain: 'Vierges, Martyres',
    desc: 'Vierge romaine du IVe siècle, martyrisée sous Julien l\'Apostat. Fouettée à mort pour avoir refusé de renier sa foi.' },
  { mmdd: '12-03', name: 'Saint François-Xavier', domain: 'Confesseurs, Missionnaires',
    desc: 'Missionnaire jésuite du XVIe siècle, apôtre des Indes et du Japon. Plus grand missionnaire des temps modernes. Patron des missions.' },
  { mmdd: '12-04', name: 'Saint Pierre Chrysologue', domain: 'Évêques, Docteurs',
    desc: 'Évêque de Ravenne au Ve siècle. Surnommé Parole d\'or pour l\'éloquence de ses homéries. Docteur de l\'Église.' },
  { mmdd: '12-05', name: 'Saint Sabas de Mar Saba', domain: 'Abbés',
    desc: 'Moine palestinien du VIe siècle, fondateur du monastère de Mar Saba dans le désert de Judée. Père du monachisme palestinien.' },
  { mmdd: '12-06', name: 'Saint Nicolas', domain: 'Évêques',
    desc: 'Évêque de Myre en Asie Mineure au IVe siècle. Connu pour ses miracles et sa générosité envers les enfants. Patron de la Lorraine et des écoliers.' },
  { mmdd: '12-07', name: 'Saint Ambroise de Milan', domain: 'Évêques, Docteurs',
    desc: 'Évêque de Milan au IVe siècle, Père de l\'Église latine. Convertit saint Augustin. Auteur de traités théologiques et de l\'hymne Te Deum.' },
  { mmdd: '12-08', name: 'Immaculée Conception', domain: 'Fête de la Vierge',
    desc: 'La Vierge Marie a été préservée du péché originel dès le premier instant de sa conception. Dogme proclamé par Pie IX en 1854.' },
  { mmdd: '12-09', name: 'Sainte Léocadie', domain: 'Vierges, Martyres',
    desc: 'Vierge de Tolède en Espagne au IVe siècle, martyre sous Dioclétien. Patronne de la ville de Tolède.' },
  { mmdd: '12-10', name: 'Saint Miltiade', domain: 'Papes, Martyrs',
    desc: 'Pape du IVe siècle, martyr sous Dioclétien. Il gouverna l\'Église pendant la paix constantinienne et fit construire les premières basiliques romaines.' },
  { mmdd: '12-11', name: 'Saint Damase Ier', domain: 'Papes',
    desc: 'Pape du IVe siècle. Restaura les catacombes, commanda la Vulgate à saint Jérôme et défendit la primauté du siège de Rome.' },
  { mmdd: '12-12', name: 'Sainte Victoire de Rome', domain: 'Vierges, Martyres',
    desc: 'Vierge et martyre romaine du IIIe siècle, persécutée sous l\'empereur Dèce. Morte pour avoir refusé d\'épouser un païen.' },
  { mmdd: '12-13', name: 'Sainte Luce (Lucie)', domain: 'Vierges, Martyres',
    desc: 'Vierge sicilienne du IVe siècle, martyre sous Dioclétien. Les yeux arrachés, elle recouvra miraculeusement la vue. Patronne des aveugles et des yeux.' },
  { mmdd: '12-14', name: 'Saint Nicaise de Reims', domain: 'Évêques, Martyrs',
    desc: 'Évêque de Reims au Ve siècle, massacré par des barbares avec sa sœur Eutropie. Patron de la ville de Reims.' },
  { mmdd: '12-15', name: 'Sainte Mesme', domain: 'Vierges, Ermites',
    desc: 'Vierge ermite de Touraine au Ve siècle. Disciple de saint Martin, elle vécut en recluse dans une grotte près de Chinon.' },
  { mmdd: '12-16', name: 'Sainte Adélaïde de Bourgogne', domain: 'Impératrices',
    desc: 'Impératrice du Saint-Empire au Xe siècle. Régente pour son fils Otton II, fondatrice de monastères. Patronne des veuves.' },
  { mmdd: '12-17', name: 'Saint Lazare de Béthanie', domain: 'Confesseurs',
    desc: 'Frère de Marthe et Marie, ressuscité par Jésus. Selon la tradition provençale, il devint le premier évêque de Marseille.' },
  { mmdd: '12-18', name: 'Saint Gatien de Tours', domain: 'Évêques',
    desc: 'Premier évêque de Tours au IIIe siècle, envoyé de Rome évangéliser la Gaule lyonnaise. Fondateur de l\'Église de Tours.' },
  { mmdd: '12-19', name: 'Saint Némésien de Carthage', domain: 'Martyrs',
    desc: 'Évêque de Carthage au IIIe siècle, martyr sous Valérien. Mort dans les mines avec ses compagnons pour avoir refusé d\'apostasier.' },
  { mmdd: '12-20', name: 'Saint Ignace d\'Antioche', domain: 'Évêques, Martyrs',
    desc: 'Évêque d\'Antioche au IIe siècle, condamné aux bêtes. Sur la route de Rome, il écrivit sept lettres qui sont des trésors de la foi primitive.' },
  { mmdd: '12-21', name: 'Saint Thomas apôtre', domain: 'Apôtres',
    desc: 'L\'apôtre Didyme, qui toucha les plaies du Christ ressuscité. Évangélisa l\'Inde où il subit le martyre. Patron des architectes.' },
  { mmdd: '12-22', name: 'Saint Flavien de Rome', domain: 'Martyrs',
    desc: 'Martyr romain du IVe siècle, prêtre et confesseur pendant la persécution de Dioclétien.' },
  { mmdd: '12-23', name: 'Saint Servule de Rome', domain: 'Confesseurs',
    desc: 'Mendiant romain du VIe siècle, paralytique de naissance. Il passait ses jours devant l\'église Saint-Clément, priant et édifiant les passants.' },
  { mmdd: '12-24', name: 'Sainte Tarsile', domain: 'Vierges',
    desc: 'Vierge romaine du VIe siècle, tante de saint Grégoire le Grand. Menait une vie de prière et de pénitence avec ses sœurs.' },
  { mmdd: '12-25', name: 'Noël — Nativité du Seigneur', domain: 'Fête du Seigneur',
    desc: 'Naissance de Jésus-Christ à Bethléem. La plus grande fête chrétienne après Pâques. Dans la France de la Belle Époque, messe de minuit, crèche et réveillon.' },
  { mmdd: '12-26', name: 'Saint Étienne', domain: 'Protomartyr',
    desc: 'Premier martyr chrétien, l\'un des sept diacres de la communauté de Jérusalem. Lapidé pour sa foi. Très célébré en Alsace-Lorraine.' },
  { mmdd: '12-27', name: 'Saint Jean l\'Évangéliste', domain: 'Apôtres, Évangélistes',
    desc: 'Le disciple que Jésus aimait, auteur du quatrième évangile et de l\'Apocalypse. Patron des théologiens et des écrivains.' },
  { mmdd: '12-28', name: 'Saints Innocents', domain: 'Martyrs',
    desc: 'Les enfants de moins de deux ans massacrés par Hérode le Grand à Bethléem. Premiers martyrs chrétiens, fêtés dès le Ve siècle.' },
  { mmdd: '12-29', name: 'Saint Thomas Becket', domain: 'Évêques, Martyrs',
    desc: 'Archevêque de Cantorbéry au XIIe siècle, assassiné dans sa cathédrale par les chevaliers du roi Henri II d\'Angleterre.' },
  { mmdd: '12-30', name: 'Saint Roger de Cannes', domain: 'Évêques',
    desc: 'Évêque de Cannes en Italie du Sud au XIIe siècle. Connu pour sa sainteté et son dévouement aux pauvres.' },
  { mmdd: '12-31', name: 'Saint Sylvestre Ier', domain: 'Papes',
    desc: 'Pape du IVe siècle, contemporain de l\'empereur Constantin. Il gouverna l\'Église au moment de l\'édit de Milan et du concile de Nicée.' },
];

// Jours de février pour les années bissextiles (29 février)
const saintsFeb29 = { mmdd: '02-29', name: 'Saint Oswald', domain: 'Évêques',
  desc: 'Évêque de Worcester puis archevêque d\'York au Xe siècle. Connu pour sa sainteté et son travail missionnaire en Angleterre.' };

module.exports = { saints, saintsFeb29 };
